// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: types/bbc.proto

package proto.types;

public final class bbc {
  private bbc() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface BbcDecisionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.types.BbcDecision)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.proto.types.Meta m = 1;</code>
     */
    boolean hasM();
    /**
     * <code>.proto.types.Meta m = 1;</code>
     */
    proto.types.meta.Meta getM();
    /**
     * <code>.proto.types.Meta m = 1;</code>
     */
    proto.types.meta.MetaOrBuilder getMOrBuilder();

    /**
     * <code>int32 decosion = 2;</code>
     */
    int getDecosion();

    /**
     * <code>int32 sender = 3;</code>
     */
    int getSender();
  }
  /**
   * Protobuf type {@code proto.types.BbcDecision}
   */
  public  static final class BbcDecision extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.types.BbcDecision)
      BbcDecisionOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use BbcDecision.newBuilder() to construct.
    private BbcDecision(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BbcDecision() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private BbcDecision(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              proto.types.meta.Meta.Builder subBuilder = null;
              if (m_ != null) {
                subBuilder = m_.toBuilder();
              }
              m_ = input.readMessage(proto.types.meta.Meta.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(m_);
                m_ = subBuilder.buildPartial();
              }

              break;
            }
            case 16: {

              decosion_ = input.readInt32();
              break;
            }
            case 24: {

              sender_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.types.bbc.internal_static_proto_types_BbcDecision_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.types.bbc.internal_static_proto_types_BbcDecision_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.types.bbc.BbcDecision.class, proto.types.bbc.BbcDecision.Builder.class);
    }

    public static final int M_FIELD_NUMBER = 1;
    private proto.types.meta.Meta m_;
    /**
     * <code>.proto.types.Meta m = 1;</code>
     */
    public boolean hasM() {
      return m_ != null;
    }
    /**
     * <code>.proto.types.Meta m = 1;</code>
     */
    public proto.types.meta.Meta getM() {
      return m_ == null ? proto.types.meta.Meta.getDefaultInstance() : m_;
    }
    /**
     * <code>.proto.types.Meta m = 1;</code>
     */
    public proto.types.meta.MetaOrBuilder getMOrBuilder() {
      return getM();
    }

    public static final int DECOSION_FIELD_NUMBER = 2;
    private int decosion_;
    /**
     * <code>int32 decosion = 2;</code>
     */
    public int getDecosion() {
      return decosion_;
    }

    public static final int SENDER_FIELD_NUMBER = 3;
    private int sender_;
    /**
     * <code>int32 sender = 3;</code>
     */
    public int getSender() {
      return sender_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (m_ != null) {
        output.writeMessage(1, getM());
      }
      if (decosion_ != 0) {
        output.writeInt32(2, decosion_);
      }
      if (sender_ != 0) {
        output.writeInt32(3, sender_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (m_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getM());
      }
      if (decosion_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, decosion_);
      }
      if (sender_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, sender_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto.types.bbc.BbcDecision)) {
        return super.equals(obj);
      }
      proto.types.bbc.BbcDecision other = (proto.types.bbc.BbcDecision) obj;

      if (hasM() != other.hasM()) return false;
      if (hasM()) {
        if (!getM()
            .equals(other.getM())) return false;
      }
      if (getDecosion()
          != other.getDecosion()) return false;
      if (getSender()
          != other.getSender()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasM()) {
        hash = (37 * hash) + M_FIELD_NUMBER;
        hash = (53 * hash) + getM().hashCode();
      }
      hash = (37 * hash) + DECOSION_FIELD_NUMBER;
      hash = (53 * hash) + getDecosion();
      hash = (37 * hash) + SENDER_FIELD_NUMBER;
      hash = (53 * hash) + getSender();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto.types.bbc.BbcDecision parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.types.bbc.BbcDecision parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.types.bbc.BbcDecision parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.types.bbc.BbcDecision parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.types.bbc.BbcDecision parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.types.bbc.BbcDecision parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.types.bbc.BbcDecision parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.types.bbc.BbcDecision parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.types.bbc.BbcDecision parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static proto.types.bbc.BbcDecision parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.types.bbc.BbcDecision parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.types.bbc.BbcDecision parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto.types.bbc.BbcDecision prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.types.BbcDecision}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.types.BbcDecision)
        proto.types.bbc.BbcDecisionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.types.bbc.internal_static_proto_types_BbcDecision_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.types.bbc.internal_static_proto_types_BbcDecision_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.types.bbc.BbcDecision.class, proto.types.bbc.BbcDecision.Builder.class);
      }

      // Construct using proto.types.bbc.BbcDecision.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (mBuilder_ == null) {
          m_ = null;
        } else {
          m_ = null;
          mBuilder_ = null;
        }
        decosion_ = 0;

        sender_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.types.bbc.internal_static_proto_types_BbcDecision_descriptor;
      }

      @java.lang.Override
      public proto.types.bbc.BbcDecision getDefaultInstanceForType() {
        return proto.types.bbc.BbcDecision.getDefaultInstance();
      }

      @java.lang.Override
      public proto.types.bbc.BbcDecision build() {
        proto.types.bbc.BbcDecision result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public proto.types.bbc.BbcDecision buildPartial() {
        proto.types.bbc.BbcDecision result = new proto.types.bbc.BbcDecision(this);
        if (mBuilder_ == null) {
          result.m_ = m_;
        } else {
          result.m_ = mBuilder_.build();
        }
        result.decosion_ = decosion_;
        result.sender_ = sender_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.types.bbc.BbcDecision) {
          return mergeFrom((proto.types.bbc.BbcDecision)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.types.bbc.BbcDecision other) {
        if (other == proto.types.bbc.BbcDecision.getDefaultInstance()) return this;
        if (other.hasM()) {
          mergeM(other.getM());
        }
        if (other.getDecosion() != 0) {
          setDecosion(other.getDecosion());
        }
        if (other.getSender() != 0) {
          setSender(other.getSender());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.types.bbc.BbcDecision parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.types.bbc.BbcDecision) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private proto.types.meta.Meta m_;
      private com.google.protobuf.SingleFieldBuilderV3<
          proto.types.meta.Meta, proto.types.meta.Meta.Builder, proto.types.meta.MetaOrBuilder> mBuilder_;
      /**
       * <code>.proto.types.Meta m = 1;</code>
       */
      public boolean hasM() {
        return mBuilder_ != null || m_ != null;
      }
      /**
       * <code>.proto.types.Meta m = 1;</code>
       */
      public proto.types.meta.Meta getM() {
        if (mBuilder_ == null) {
          return m_ == null ? proto.types.meta.Meta.getDefaultInstance() : m_;
        } else {
          return mBuilder_.getMessage();
        }
      }
      /**
       * <code>.proto.types.Meta m = 1;</code>
       */
      public Builder setM(proto.types.meta.Meta value) {
        if (mBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          m_ = value;
          onChanged();
        } else {
          mBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.proto.types.Meta m = 1;</code>
       */
      public Builder setM(
          proto.types.meta.Meta.Builder builderForValue) {
        if (mBuilder_ == null) {
          m_ = builderForValue.build();
          onChanged();
        } else {
          mBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.proto.types.Meta m = 1;</code>
       */
      public Builder mergeM(proto.types.meta.Meta value) {
        if (mBuilder_ == null) {
          if (m_ != null) {
            m_ =
              proto.types.meta.Meta.newBuilder(m_).mergeFrom(value).buildPartial();
          } else {
            m_ = value;
          }
          onChanged();
        } else {
          mBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.proto.types.Meta m = 1;</code>
       */
      public Builder clearM() {
        if (mBuilder_ == null) {
          m_ = null;
          onChanged();
        } else {
          m_ = null;
          mBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.proto.types.Meta m = 1;</code>
       */
      public proto.types.meta.Meta.Builder getMBuilder() {
        
        onChanged();
        return getMFieldBuilder().getBuilder();
      }
      /**
       * <code>.proto.types.Meta m = 1;</code>
       */
      public proto.types.meta.MetaOrBuilder getMOrBuilder() {
        if (mBuilder_ != null) {
          return mBuilder_.getMessageOrBuilder();
        } else {
          return m_ == null ?
              proto.types.meta.Meta.getDefaultInstance() : m_;
        }
      }
      /**
       * <code>.proto.types.Meta m = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          proto.types.meta.Meta, proto.types.meta.Meta.Builder, proto.types.meta.MetaOrBuilder> 
          getMFieldBuilder() {
        if (mBuilder_ == null) {
          mBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              proto.types.meta.Meta, proto.types.meta.Meta.Builder, proto.types.meta.MetaOrBuilder>(
                  getM(),
                  getParentForChildren(),
                  isClean());
          m_ = null;
        }
        return mBuilder_;
      }

      private int decosion_ ;
      /**
       * <code>int32 decosion = 2;</code>
       */
      public int getDecosion() {
        return decosion_;
      }
      /**
       * <code>int32 decosion = 2;</code>
       */
      public Builder setDecosion(int value) {
        
        decosion_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 decosion = 2;</code>
       */
      public Builder clearDecosion() {
        
        decosion_ = 0;
        onChanged();
        return this;
      }

      private int sender_ ;
      /**
       * <code>int32 sender = 3;</code>
       */
      public int getSender() {
        return sender_;
      }
      /**
       * <code>int32 sender = 3;</code>
       */
      public Builder setSender(int value) {
        
        sender_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 sender = 3;</code>
       */
      public Builder clearSender() {
        
        sender_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto.types.BbcDecision)
    }

    // @@protoc_insertion_point(class_scope:proto.types.BbcDecision)
    private static final proto.types.bbc.BbcDecision DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto.types.bbc.BbcDecision();
    }

    public static proto.types.bbc.BbcDecision getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BbcDecision>
        PARSER = new com.google.protobuf.AbstractParser<BbcDecision>() {
      @java.lang.Override
      public BbcDecision parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BbcDecision(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BbcDecision> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BbcDecision> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public proto.types.bbc.BbcDecision getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface BbcMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.types.BbcMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.proto.types.Meta m = 1;</code>
     */
    boolean hasM();
    /**
     * <code>.proto.types.Meta m = 1;</code>
     */
    proto.types.meta.Meta getM();
    /**
     * <code>.proto.types.Meta m = 1;</code>
     */
    proto.types.meta.MetaOrBuilder getMOrBuilder();

    /**
     * <code>bool vote = 2;</code>
     */
    boolean getVote();

    /**
     * <code>.proto.types.BlockHeader next = 3;</code>
     */
    boolean hasNext();
    /**
     * <code>.proto.types.BlockHeader next = 3;</code>
     */
    proto.types.block.BlockHeader getNext();
    /**
     * <code>.proto.types.BlockHeader next = 3;</code>
     */
    proto.types.block.BlockHeaderOrBuilder getNextOrBuilder();

    /**
     * <code>int32 height = 4;</code>
     */
    int getHeight();

    /**
     * <code>int32 sender = 5;</code>
     */
    int getSender();
  }
  /**
   * Protobuf type {@code proto.types.BbcMsg}
   */
  public  static final class BbcMsg extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.types.BbcMsg)
      BbcMsgOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use BbcMsg.newBuilder() to construct.
    private BbcMsg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BbcMsg() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private BbcMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              proto.types.meta.Meta.Builder subBuilder = null;
              if (m_ != null) {
                subBuilder = m_.toBuilder();
              }
              m_ = input.readMessage(proto.types.meta.Meta.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(m_);
                m_ = subBuilder.buildPartial();
              }

              break;
            }
            case 16: {

              vote_ = input.readBool();
              break;
            }
            case 26: {
              proto.types.block.BlockHeader.Builder subBuilder = null;
              if (next_ != null) {
                subBuilder = next_.toBuilder();
              }
              next_ = input.readMessage(proto.types.block.BlockHeader.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(next_);
                next_ = subBuilder.buildPartial();
              }

              break;
            }
            case 32: {

              height_ = input.readInt32();
              break;
            }
            case 40: {

              sender_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.types.bbc.internal_static_proto_types_BbcMsg_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.types.bbc.internal_static_proto_types_BbcMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.types.bbc.BbcMsg.class, proto.types.bbc.BbcMsg.Builder.class);
    }

    public static final int M_FIELD_NUMBER = 1;
    private proto.types.meta.Meta m_;
    /**
     * <code>.proto.types.Meta m = 1;</code>
     */
    public boolean hasM() {
      return m_ != null;
    }
    /**
     * <code>.proto.types.Meta m = 1;</code>
     */
    public proto.types.meta.Meta getM() {
      return m_ == null ? proto.types.meta.Meta.getDefaultInstance() : m_;
    }
    /**
     * <code>.proto.types.Meta m = 1;</code>
     */
    public proto.types.meta.MetaOrBuilder getMOrBuilder() {
      return getM();
    }

    public static final int VOTE_FIELD_NUMBER = 2;
    private boolean vote_;
    /**
     * <code>bool vote = 2;</code>
     */
    public boolean getVote() {
      return vote_;
    }

    public static final int NEXT_FIELD_NUMBER = 3;
    private proto.types.block.BlockHeader next_;
    /**
     * <code>.proto.types.BlockHeader next = 3;</code>
     */
    public boolean hasNext() {
      return next_ != null;
    }
    /**
     * <code>.proto.types.BlockHeader next = 3;</code>
     */
    public proto.types.block.BlockHeader getNext() {
      return next_ == null ? proto.types.block.BlockHeader.getDefaultInstance() : next_;
    }
    /**
     * <code>.proto.types.BlockHeader next = 3;</code>
     */
    public proto.types.block.BlockHeaderOrBuilder getNextOrBuilder() {
      return getNext();
    }

    public static final int HEIGHT_FIELD_NUMBER = 4;
    private int height_;
    /**
     * <code>int32 height = 4;</code>
     */
    public int getHeight() {
      return height_;
    }

    public static final int SENDER_FIELD_NUMBER = 5;
    private int sender_;
    /**
     * <code>int32 sender = 5;</code>
     */
    public int getSender() {
      return sender_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (m_ != null) {
        output.writeMessage(1, getM());
      }
      if (vote_ != false) {
        output.writeBool(2, vote_);
      }
      if (next_ != null) {
        output.writeMessage(3, getNext());
      }
      if (height_ != 0) {
        output.writeInt32(4, height_);
      }
      if (sender_ != 0) {
        output.writeInt32(5, sender_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (m_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getM());
      }
      if (vote_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, vote_);
      }
      if (next_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getNext());
      }
      if (height_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, height_);
      }
      if (sender_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, sender_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto.types.bbc.BbcMsg)) {
        return super.equals(obj);
      }
      proto.types.bbc.BbcMsg other = (proto.types.bbc.BbcMsg) obj;

      if (hasM() != other.hasM()) return false;
      if (hasM()) {
        if (!getM()
            .equals(other.getM())) return false;
      }
      if (getVote()
          != other.getVote()) return false;
      if (hasNext() != other.hasNext()) return false;
      if (hasNext()) {
        if (!getNext()
            .equals(other.getNext())) return false;
      }
      if (getHeight()
          != other.getHeight()) return false;
      if (getSender()
          != other.getSender()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasM()) {
        hash = (37 * hash) + M_FIELD_NUMBER;
        hash = (53 * hash) + getM().hashCode();
      }
      hash = (37 * hash) + VOTE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getVote());
      if (hasNext()) {
        hash = (37 * hash) + NEXT_FIELD_NUMBER;
        hash = (53 * hash) + getNext().hashCode();
      }
      hash = (37 * hash) + HEIGHT_FIELD_NUMBER;
      hash = (53 * hash) + getHeight();
      hash = (37 * hash) + SENDER_FIELD_NUMBER;
      hash = (53 * hash) + getSender();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto.types.bbc.BbcMsg parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.types.bbc.BbcMsg parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.types.bbc.BbcMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.types.bbc.BbcMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.types.bbc.BbcMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.types.bbc.BbcMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.types.bbc.BbcMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.types.bbc.BbcMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.types.bbc.BbcMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static proto.types.bbc.BbcMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.types.bbc.BbcMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.types.bbc.BbcMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto.types.bbc.BbcMsg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.types.BbcMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.types.BbcMsg)
        proto.types.bbc.BbcMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.types.bbc.internal_static_proto_types_BbcMsg_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.types.bbc.internal_static_proto_types_BbcMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.types.bbc.BbcMsg.class, proto.types.bbc.BbcMsg.Builder.class);
      }

      // Construct using proto.types.bbc.BbcMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (mBuilder_ == null) {
          m_ = null;
        } else {
          m_ = null;
          mBuilder_ = null;
        }
        vote_ = false;

        if (nextBuilder_ == null) {
          next_ = null;
        } else {
          next_ = null;
          nextBuilder_ = null;
        }
        height_ = 0;

        sender_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.types.bbc.internal_static_proto_types_BbcMsg_descriptor;
      }

      @java.lang.Override
      public proto.types.bbc.BbcMsg getDefaultInstanceForType() {
        return proto.types.bbc.BbcMsg.getDefaultInstance();
      }

      @java.lang.Override
      public proto.types.bbc.BbcMsg build() {
        proto.types.bbc.BbcMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public proto.types.bbc.BbcMsg buildPartial() {
        proto.types.bbc.BbcMsg result = new proto.types.bbc.BbcMsg(this);
        if (mBuilder_ == null) {
          result.m_ = m_;
        } else {
          result.m_ = mBuilder_.build();
        }
        result.vote_ = vote_;
        if (nextBuilder_ == null) {
          result.next_ = next_;
        } else {
          result.next_ = nextBuilder_.build();
        }
        result.height_ = height_;
        result.sender_ = sender_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.types.bbc.BbcMsg) {
          return mergeFrom((proto.types.bbc.BbcMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.types.bbc.BbcMsg other) {
        if (other == proto.types.bbc.BbcMsg.getDefaultInstance()) return this;
        if (other.hasM()) {
          mergeM(other.getM());
        }
        if (other.getVote() != false) {
          setVote(other.getVote());
        }
        if (other.hasNext()) {
          mergeNext(other.getNext());
        }
        if (other.getHeight() != 0) {
          setHeight(other.getHeight());
        }
        if (other.getSender() != 0) {
          setSender(other.getSender());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.types.bbc.BbcMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.types.bbc.BbcMsg) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private proto.types.meta.Meta m_;
      private com.google.protobuf.SingleFieldBuilderV3<
          proto.types.meta.Meta, proto.types.meta.Meta.Builder, proto.types.meta.MetaOrBuilder> mBuilder_;
      /**
       * <code>.proto.types.Meta m = 1;</code>
       */
      public boolean hasM() {
        return mBuilder_ != null || m_ != null;
      }
      /**
       * <code>.proto.types.Meta m = 1;</code>
       */
      public proto.types.meta.Meta getM() {
        if (mBuilder_ == null) {
          return m_ == null ? proto.types.meta.Meta.getDefaultInstance() : m_;
        } else {
          return mBuilder_.getMessage();
        }
      }
      /**
       * <code>.proto.types.Meta m = 1;</code>
       */
      public Builder setM(proto.types.meta.Meta value) {
        if (mBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          m_ = value;
          onChanged();
        } else {
          mBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.proto.types.Meta m = 1;</code>
       */
      public Builder setM(
          proto.types.meta.Meta.Builder builderForValue) {
        if (mBuilder_ == null) {
          m_ = builderForValue.build();
          onChanged();
        } else {
          mBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.proto.types.Meta m = 1;</code>
       */
      public Builder mergeM(proto.types.meta.Meta value) {
        if (mBuilder_ == null) {
          if (m_ != null) {
            m_ =
              proto.types.meta.Meta.newBuilder(m_).mergeFrom(value).buildPartial();
          } else {
            m_ = value;
          }
          onChanged();
        } else {
          mBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.proto.types.Meta m = 1;</code>
       */
      public Builder clearM() {
        if (mBuilder_ == null) {
          m_ = null;
          onChanged();
        } else {
          m_ = null;
          mBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.proto.types.Meta m = 1;</code>
       */
      public proto.types.meta.Meta.Builder getMBuilder() {
        
        onChanged();
        return getMFieldBuilder().getBuilder();
      }
      /**
       * <code>.proto.types.Meta m = 1;</code>
       */
      public proto.types.meta.MetaOrBuilder getMOrBuilder() {
        if (mBuilder_ != null) {
          return mBuilder_.getMessageOrBuilder();
        } else {
          return m_ == null ?
              proto.types.meta.Meta.getDefaultInstance() : m_;
        }
      }
      /**
       * <code>.proto.types.Meta m = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          proto.types.meta.Meta, proto.types.meta.Meta.Builder, proto.types.meta.MetaOrBuilder> 
          getMFieldBuilder() {
        if (mBuilder_ == null) {
          mBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              proto.types.meta.Meta, proto.types.meta.Meta.Builder, proto.types.meta.MetaOrBuilder>(
                  getM(),
                  getParentForChildren(),
                  isClean());
          m_ = null;
        }
        return mBuilder_;
      }

      private boolean vote_ ;
      /**
       * <code>bool vote = 2;</code>
       */
      public boolean getVote() {
        return vote_;
      }
      /**
       * <code>bool vote = 2;</code>
       */
      public Builder setVote(boolean value) {
        
        vote_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool vote = 2;</code>
       */
      public Builder clearVote() {
        
        vote_ = false;
        onChanged();
        return this;
      }

      private proto.types.block.BlockHeader next_;
      private com.google.protobuf.SingleFieldBuilderV3<
          proto.types.block.BlockHeader, proto.types.block.BlockHeader.Builder, proto.types.block.BlockHeaderOrBuilder> nextBuilder_;
      /**
       * <code>.proto.types.BlockHeader next = 3;</code>
       */
      public boolean hasNext() {
        return nextBuilder_ != null || next_ != null;
      }
      /**
       * <code>.proto.types.BlockHeader next = 3;</code>
       */
      public proto.types.block.BlockHeader getNext() {
        if (nextBuilder_ == null) {
          return next_ == null ? proto.types.block.BlockHeader.getDefaultInstance() : next_;
        } else {
          return nextBuilder_.getMessage();
        }
      }
      /**
       * <code>.proto.types.BlockHeader next = 3;</code>
       */
      public Builder setNext(proto.types.block.BlockHeader value) {
        if (nextBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          next_ = value;
          onChanged();
        } else {
          nextBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.proto.types.BlockHeader next = 3;</code>
       */
      public Builder setNext(
          proto.types.block.BlockHeader.Builder builderForValue) {
        if (nextBuilder_ == null) {
          next_ = builderForValue.build();
          onChanged();
        } else {
          nextBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.proto.types.BlockHeader next = 3;</code>
       */
      public Builder mergeNext(proto.types.block.BlockHeader value) {
        if (nextBuilder_ == null) {
          if (next_ != null) {
            next_ =
              proto.types.block.BlockHeader.newBuilder(next_).mergeFrom(value).buildPartial();
          } else {
            next_ = value;
          }
          onChanged();
        } else {
          nextBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.proto.types.BlockHeader next = 3;</code>
       */
      public Builder clearNext() {
        if (nextBuilder_ == null) {
          next_ = null;
          onChanged();
        } else {
          next_ = null;
          nextBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.proto.types.BlockHeader next = 3;</code>
       */
      public proto.types.block.BlockHeader.Builder getNextBuilder() {
        
        onChanged();
        return getNextFieldBuilder().getBuilder();
      }
      /**
       * <code>.proto.types.BlockHeader next = 3;</code>
       */
      public proto.types.block.BlockHeaderOrBuilder getNextOrBuilder() {
        if (nextBuilder_ != null) {
          return nextBuilder_.getMessageOrBuilder();
        } else {
          return next_ == null ?
              proto.types.block.BlockHeader.getDefaultInstance() : next_;
        }
      }
      /**
       * <code>.proto.types.BlockHeader next = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          proto.types.block.BlockHeader, proto.types.block.BlockHeader.Builder, proto.types.block.BlockHeaderOrBuilder> 
          getNextFieldBuilder() {
        if (nextBuilder_ == null) {
          nextBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              proto.types.block.BlockHeader, proto.types.block.BlockHeader.Builder, proto.types.block.BlockHeaderOrBuilder>(
                  getNext(),
                  getParentForChildren(),
                  isClean());
          next_ = null;
        }
        return nextBuilder_;
      }

      private int height_ ;
      /**
       * <code>int32 height = 4;</code>
       */
      public int getHeight() {
        return height_;
      }
      /**
       * <code>int32 height = 4;</code>
       */
      public Builder setHeight(int value) {
        
        height_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 height = 4;</code>
       */
      public Builder clearHeight() {
        
        height_ = 0;
        onChanged();
        return this;
      }

      private int sender_ ;
      /**
       * <code>int32 sender = 5;</code>
       */
      public int getSender() {
        return sender_;
      }
      /**
       * <code>int32 sender = 5;</code>
       */
      public Builder setSender(int value) {
        
        sender_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 sender = 5;</code>
       */
      public Builder clearSender() {
        
        sender_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto.types.BbcMsg)
    }

    // @@protoc_insertion_point(class_scope:proto.types.BbcMsg)
    private static final proto.types.bbc.BbcMsg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto.types.bbc.BbcMsg();
    }

    public static proto.types.bbc.BbcMsg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BbcMsg>
        PARSER = new com.google.protobuf.AbstractParser<BbcMsg>() {
      @java.lang.Override
      public BbcMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BbcMsg(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BbcMsg> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BbcMsg> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public proto.types.bbc.BbcMsg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_types_BbcDecision_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_types_BbcDecision_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_types_BbcMsg_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_types_BbcMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017types/bbc.proto\022\013proto.types\032\020types/me" +
      "ta.proto\032\021types/block.proto\"M\n\013BbcDecisi" +
      "on\022\034\n\001m\030\001 \001(\0132\021.proto.types.Meta\022\020\n\010deco" +
      "sion\030\002 \001(\005\022\016\n\006sender\030\003 \001(\005\"|\n\006BbcMsg\022\034\n\001" +
      "m\030\001 \001(\0132\021.proto.types.Meta\022\014\n\004vote\030\002 \001(\010" +
      "\022&\n\004next\030\003 \001(\0132\030.proto.types.BlockHeader" +
      "\022\016\n\006height\030\004 \001(\005\022\016\n\006sender\030\005 \001(\005B\022\n\013prot" +
      "o.typesB\003bbcb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          proto.types.meta.getDescriptor(),
          proto.types.block.getDescriptor(),
        }, assigner);
    internal_static_proto_types_BbcDecision_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_types_BbcDecision_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_types_BbcDecision_descriptor,
        new java.lang.String[] { "M", "Decosion", "Sender", });
    internal_static_proto_types_BbcMsg_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_proto_types_BbcMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_types_BbcMsg_descriptor,
        new java.lang.String[] { "M", "Vote", "Next", "Height", "Sender", });
    proto.types.meta.getDescriptor();
    proto.types.block.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
