// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: types/client.proto

package proto.types;

public final class client {
  private client() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AcceptedOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.types.Accepted)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bool accepted = 1;</code>
     */
    boolean getAccepted();

    /**
     * <code>.proto.types.TxID txID = 2;</code>
     */
    boolean hasTxID();
    /**
     * <code>.proto.types.TxID txID = 2;</code>
     */
    proto.types.transaction.TxID getTxID();
    /**
     * <code>.proto.types.TxID txID = 2;</code>
     */
    proto.types.transaction.TxIDOrBuilder getTxIDOrBuilder();
  }
  /**
   * Protobuf type {@code proto.types.Accepted}
   */
  public  static final class Accepted extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.types.Accepted)
      AcceptedOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Accepted.newBuilder() to construct.
    private Accepted(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Accepted() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Accepted(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              accepted_ = input.readBool();
              break;
            }
            case 18: {
              proto.types.transaction.TxID.Builder subBuilder = null;
              if (txID_ != null) {
                subBuilder = txID_.toBuilder();
              }
              txID_ = input.readMessage(proto.types.transaction.TxID.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(txID_);
                txID_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.types.client.internal_static_proto_types_Accepted_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.types.client.internal_static_proto_types_Accepted_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.types.client.Accepted.class, proto.types.client.Accepted.Builder.class);
    }

    public static final int ACCEPTED_FIELD_NUMBER = 1;
    private boolean accepted_;
    /**
     * <code>bool accepted = 1;</code>
     */
    public boolean getAccepted() {
      return accepted_;
    }

    public static final int TXID_FIELD_NUMBER = 2;
    private proto.types.transaction.TxID txID_;
    /**
     * <code>.proto.types.TxID txID = 2;</code>
     */
    public boolean hasTxID() {
      return txID_ != null;
    }
    /**
     * <code>.proto.types.TxID txID = 2;</code>
     */
    public proto.types.transaction.TxID getTxID() {
      return txID_ == null ? proto.types.transaction.TxID.getDefaultInstance() : txID_;
    }
    /**
     * <code>.proto.types.TxID txID = 2;</code>
     */
    public proto.types.transaction.TxIDOrBuilder getTxIDOrBuilder() {
      return getTxID();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (accepted_ != false) {
        output.writeBool(1, accepted_);
      }
      if (txID_ != null) {
        output.writeMessage(2, getTxID());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (accepted_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, accepted_);
      }
      if (txID_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getTxID());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto.types.client.Accepted)) {
        return super.equals(obj);
      }
      proto.types.client.Accepted other = (proto.types.client.Accepted) obj;

      if (getAccepted()
          != other.getAccepted()) return false;
      if (hasTxID() != other.hasTxID()) return false;
      if (hasTxID()) {
        if (!getTxID()
            .equals(other.getTxID())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ACCEPTED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getAccepted());
      if (hasTxID()) {
        hash = (37 * hash) + TXID_FIELD_NUMBER;
        hash = (53 * hash) + getTxID().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto.types.client.Accepted parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.types.client.Accepted parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.types.client.Accepted parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.types.client.Accepted parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.types.client.Accepted parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.types.client.Accepted parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.types.client.Accepted parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.types.client.Accepted parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.types.client.Accepted parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static proto.types.client.Accepted parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.types.client.Accepted parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.types.client.Accepted parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto.types.client.Accepted prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.types.Accepted}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.types.Accepted)
        proto.types.client.AcceptedOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.types.client.internal_static_proto_types_Accepted_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.types.client.internal_static_proto_types_Accepted_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.types.client.Accepted.class, proto.types.client.Accepted.Builder.class);
      }

      // Construct using proto.types.client.Accepted.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        accepted_ = false;

        if (txIDBuilder_ == null) {
          txID_ = null;
        } else {
          txID_ = null;
          txIDBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.types.client.internal_static_proto_types_Accepted_descriptor;
      }

      @java.lang.Override
      public proto.types.client.Accepted getDefaultInstanceForType() {
        return proto.types.client.Accepted.getDefaultInstance();
      }

      @java.lang.Override
      public proto.types.client.Accepted build() {
        proto.types.client.Accepted result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public proto.types.client.Accepted buildPartial() {
        proto.types.client.Accepted result = new proto.types.client.Accepted(this);
        result.accepted_ = accepted_;
        if (txIDBuilder_ == null) {
          result.txID_ = txID_;
        } else {
          result.txID_ = txIDBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.types.client.Accepted) {
          return mergeFrom((proto.types.client.Accepted)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.types.client.Accepted other) {
        if (other == proto.types.client.Accepted.getDefaultInstance()) return this;
        if (other.getAccepted() != false) {
          setAccepted(other.getAccepted());
        }
        if (other.hasTxID()) {
          mergeTxID(other.getTxID());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.types.client.Accepted parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.types.client.Accepted) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private boolean accepted_ ;
      /**
       * <code>bool accepted = 1;</code>
       */
      public boolean getAccepted() {
        return accepted_;
      }
      /**
       * <code>bool accepted = 1;</code>
       */
      public Builder setAccepted(boolean value) {
        
        accepted_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool accepted = 1;</code>
       */
      public Builder clearAccepted() {
        
        accepted_ = false;
        onChanged();
        return this;
      }

      private proto.types.transaction.TxID txID_;
      private com.google.protobuf.SingleFieldBuilderV3<
          proto.types.transaction.TxID, proto.types.transaction.TxID.Builder, proto.types.transaction.TxIDOrBuilder> txIDBuilder_;
      /**
       * <code>.proto.types.TxID txID = 2;</code>
       */
      public boolean hasTxID() {
        return txIDBuilder_ != null || txID_ != null;
      }
      /**
       * <code>.proto.types.TxID txID = 2;</code>
       */
      public proto.types.transaction.TxID getTxID() {
        if (txIDBuilder_ == null) {
          return txID_ == null ? proto.types.transaction.TxID.getDefaultInstance() : txID_;
        } else {
          return txIDBuilder_.getMessage();
        }
      }
      /**
       * <code>.proto.types.TxID txID = 2;</code>
       */
      public Builder setTxID(proto.types.transaction.TxID value) {
        if (txIDBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          txID_ = value;
          onChanged();
        } else {
          txIDBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.proto.types.TxID txID = 2;</code>
       */
      public Builder setTxID(
          proto.types.transaction.TxID.Builder builderForValue) {
        if (txIDBuilder_ == null) {
          txID_ = builderForValue.build();
          onChanged();
        } else {
          txIDBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.proto.types.TxID txID = 2;</code>
       */
      public Builder mergeTxID(proto.types.transaction.TxID value) {
        if (txIDBuilder_ == null) {
          if (txID_ != null) {
            txID_ =
              proto.types.transaction.TxID.newBuilder(txID_).mergeFrom(value).buildPartial();
          } else {
            txID_ = value;
          }
          onChanged();
        } else {
          txIDBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.proto.types.TxID txID = 2;</code>
       */
      public Builder clearTxID() {
        if (txIDBuilder_ == null) {
          txID_ = null;
          onChanged();
        } else {
          txID_ = null;
          txIDBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.proto.types.TxID txID = 2;</code>
       */
      public proto.types.transaction.TxID.Builder getTxIDBuilder() {
        
        onChanged();
        return getTxIDFieldBuilder().getBuilder();
      }
      /**
       * <code>.proto.types.TxID txID = 2;</code>
       */
      public proto.types.transaction.TxIDOrBuilder getTxIDOrBuilder() {
        if (txIDBuilder_ != null) {
          return txIDBuilder_.getMessageOrBuilder();
        } else {
          return txID_ == null ?
              proto.types.transaction.TxID.getDefaultInstance() : txID_;
        }
      }
      /**
       * <code>.proto.types.TxID txID = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          proto.types.transaction.TxID, proto.types.transaction.TxID.Builder, proto.types.transaction.TxIDOrBuilder> 
          getTxIDFieldBuilder() {
        if (txIDBuilder_ == null) {
          txIDBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              proto.types.transaction.TxID, proto.types.transaction.TxID.Builder, proto.types.transaction.TxIDOrBuilder>(
                  getTxID(),
                  getParentForChildren(),
                  isClean());
          txID_ = null;
        }
        return txIDBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto.types.Accepted)
    }

    // @@protoc_insertion_point(class_scope:proto.types.Accepted)
    private static final proto.types.client.Accepted DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto.types.client.Accepted();
    }

    public static proto.types.client.Accepted getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Accepted>
        PARSER = new com.google.protobuf.AbstractParser<Accepted>() {
      @java.lang.Override
      public Accepted parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Accepted(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Accepted> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Accepted> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public proto.types.client.Accepted getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ReadReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.types.ReadReq)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.proto.types.TxID tid = 1;</code>
     */
    boolean hasTid();
    /**
     * <code>.proto.types.TxID tid = 1;</code>
     */
    proto.types.transaction.TxID getTid();
    /**
     * <code>.proto.types.TxID tid = 1;</code>
     */
    proto.types.transaction.TxIDOrBuilder getTidOrBuilder();

    /**
     * <code>.proto.types.Transaction tx = 2;</code>
     */
    boolean hasTx();
    /**
     * <code>.proto.types.Transaction tx = 2;</code>
     */
    proto.types.transaction.Transaction getTx();
    /**
     * <code>.proto.types.Transaction tx = 2;</code>
     */
    proto.types.transaction.TransactionOrBuilder getTxOrBuilder();

    /**
     * <code>bool blocking = 3;</code>
     */
    boolean getBlocking();

    /**
     * <code>int32 cid = 4;</code>
     */
    int getCid();
  }
  /**
   * Protobuf type {@code proto.types.ReadReq}
   */
  public  static final class ReadReq extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.types.ReadReq)
      ReadReqOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ReadReq.newBuilder() to construct.
    private ReadReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ReadReq() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ReadReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              proto.types.transaction.TxID.Builder subBuilder = null;
              if (tid_ != null) {
                subBuilder = tid_.toBuilder();
              }
              tid_ = input.readMessage(proto.types.transaction.TxID.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(tid_);
                tid_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              proto.types.transaction.Transaction.Builder subBuilder = null;
              if (tx_ != null) {
                subBuilder = tx_.toBuilder();
              }
              tx_ = input.readMessage(proto.types.transaction.Transaction.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(tx_);
                tx_ = subBuilder.buildPartial();
              }

              break;
            }
            case 24: {

              blocking_ = input.readBool();
              break;
            }
            case 32: {

              cid_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.types.client.internal_static_proto_types_ReadReq_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.types.client.internal_static_proto_types_ReadReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.types.client.ReadReq.class, proto.types.client.ReadReq.Builder.class);
    }

    public static final int TID_FIELD_NUMBER = 1;
    private proto.types.transaction.TxID tid_;
    /**
     * <code>.proto.types.TxID tid = 1;</code>
     */
    public boolean hasTid() {
      return tid_ != null;
    }
    /**
     * <code>.proto.types.TxID tid = 1;</code>
     */
    public proto.types.transaction.TxID getTid() {
      return tid_ == null ? proto.types.transaction.TxID.getDefaultInstance() : tid_;
    }
    /**
     * <code>.proto.types.TxID tid = 1;</code>
     */
    public proto.types.transaction.TxIDOrBuilder getTidOrBuilder() {
      return getTid();
    }

    public static final int TX_FIELD_NUMBER = 2;
    private proto.types.transaction.Transaction tx_;
    /**
     * <code>.proto.types.Transaction tx = 2;</code>
     */
    public boolean hasTx() {
      return tx_ != null;
    }
    /**
     * <code>.proto.types.Transaction tx = 2;</code>
     */
    public proto.types.transaction.Transaction getTx() {
      return tx_ == null ? proto.types.transaction.Transaction.getDefaultInstance() : tx_;
    }
    /**
     * <code>.proto.types.Transaction tx = 2;</code>
     */
    public proto.types.transaction.TransactionOrBuilder getTxOrBuilder() {
      return getTx();
    }

    public static final int BLOCKING_FIELD_NUMBER = 3;
    private boolean blocking_;
    /**
     * <code>bool blocking = 3;</code>
     */
    public boolean getBlocking() {
      return blocking_;
    }

    public static final int CID_FIELD_NUMBER = 4;
    private int cid_;
    /**
     * <code>int32 cid = 4;</code>
     */
    public int getCid() {
      return cid_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (tid_ != null) {
        output.writeMessage(1, getTid());
      }
      if (tx_ != null) {
        output.writeMessage(2, getTx());
      }
      if (blocking_ != false) {
        output.writeBool(3, blocking_);
      }
      if (cid_ != 0) {
        output.writeInt32(4, cid_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (tid_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getTid());
      }
      if (tx_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getTx());
      }
      if (blocking_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, blocking_);
      }
      if (cid_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, cid_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto.types.client.ReadReq)) {
        return super.equals(obj);
      }
      proto.types.client.ReadReq other = (proto.types.client.ReadReq) obj;

      if (hasTid() != other.hasTid()) return false;
      if (hasTid()) {
        if (!getTid()
            .equals(other.getTid())) return false;
      }
      if (hasTx() != other.hasTx()) return false;
      if (hasTx()) {
        if (!getTx()
            .equals(other.getTx())) return false;
      }
      if (getBlocking()
          != other.getBlocking()) return false;
      if (getCid()
          != other.getCid()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasTid()) {
        hash = (37 * hash) + TID_FIELD_NUMBER;
        hash = (53 * hash) + getTid().hashCode();
      }
      if (hasTx()) {
        hash = (37 * hash) + TX_FIELD_NUMBER;
        hash = (53 * hash) + getTx().hashCode();
      }
      hash = (37 * hash) + BLOCKING_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getBlocking());
      hash = (37 * hash) + CID_FIELD_NUMBER;
      hash = (53 * hash) + getCid();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto.types.client.ReadReq parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.types.client.ReadReq parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.types.client.ReadReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.types.client.ReadReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.types.client.ReadReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.types.client.ReadReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.types.client.ReadReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.types.client.ReadReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.types.client.ReadReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static proto.types.client.ReadReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.types.client.ReadReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.types.client.ReadReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto.types.client.ReadReq prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.types.ReadReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.types.ReadReq)
        proto.types.client.ReadReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.types.client.internal_static_proto_types_ReadReq_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.types.client.internal_static_proto_types_ReadReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.types.client.ReadReq.class, proto.types.client.ReadReq.Builder.class);
      }

      // Construct using proto.types.client.ReadReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (tidBuilder_ == null) {
          tid_ = null;
        } else {
          tid_ = null;
          tidBuilder_ = null;
        }
        if (txBuilder_ == null) {
          tx_ = null;
        } else {
          tx_ = null;
          txBuilder_ = null;
        }
        blocking_ = false;

        cid_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.types.client.internal_static_proto_types_ReadReq_descriptor;
      }

      @java.lang.Override
      public proto.types.client.ReadReq getDefaultInstanceForType() {
        return proto.types.client.ReadReq.getDefaultInstance();
      }

      @java.lang.Override
      public proto.types.client.ReadReq build() {
        proto.types.client.ReadReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public proto.types.client.ReadReq buildPartial() {
        proto.types.client.ReadReq result = new proto.types.client.ReadReq(this);
        if (tidBuilder_ == null) {
          result.tid_ = tid_;
        } else {
          result.tid_ = tidBuilder_.build();
        }
        if (txBuilder_ == null) {
          result.tx_ = tx_;
        } else {
          result.tx_ = txBuilder_.build();
        }
        result.blocking_ = blocking_;
        result.cid_ = cid_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.types.client.ReadReq) {
          return mergeFrom((proto.types.client.ReadReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.types.client.ReadReq other) {
        if (other == proto.types.client.ReadReq.getDefaultInstance()) return this;
        if (other.hasTid()) {
          mergeTid(other.getTid());
        }
        if (other.hasTx()) {
          mergeTx(other.getTx());
        }
        if (other.getBlocking() != false) {
          setBlocking(other.getBlocking());
        }
        if (other.getCid() != 0) {
          setCid(other.getCid());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.types.client.ReadReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.types.client.ReadReq) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private proto.types.transaction.TxID tid_;
      private com.google.protobuf.SingleFieldBuilderV3<
          proto.types.transaction.TxID, proto.types.transaction.TxID.Builder, proto.types.transaction.TxIDOrBuilder> tidBuilder_;
      /**
       * <code>.proto.types.TxID tid = 1;</code>
       */
      public boolean hasTid() {
        return tidBuilder_ != null || tid_ != null;
      }
      /**
       * <code>.proto.types.TxID tid = 1;</code>
       */
      public proto.types.transaction.TxID getTid() {
        if (tidBuilder_ == null) {
          return tid_ == null ? proto.types.transaction.TxID.getDefaultInstance() : tid_;
        } else {
          return tidBuilder_.getMessage();
        }
      }
      /**
       * <code>.proto.types.TxID tid = 1;</code>
       */
      public Builder setTid(proto.types.transaction.TxID value) {
        if (tidBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          tid_ = value;
          onChanged();
        } else {
          tidBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.proto.types.TxID tid = 1;</code>
       */
      public Builder setTid(
          proto.types.transaction.TxID.Builder builderForValue) {
        if (tidBuilder_ == null) {
          tid_ = builderForValue.build();
          onChanged();
        } else {
          tidBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.proto.types.TxID tid = 1;</code>
       */
      public Builder mergeTid(proto.types.transaction.TxID value) {
        if (tidBuilder_ == null) {
          if (tid_ != null) {
            tid_ =
              proto.types.transaction.TxID.newBuilder(tid_).mergeFrom(value).buildPartial();
          } else {
            tid_ = value;
          }
          onChanged();
        } else {
          tidBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.proto.types.TxID tid = 1;</code>
       */
      public Builder clearTid() {
        if (tidBuilder_ == null) {
          tid_ = null;
          onChanged();
        } else {
          tid_ = null;
          tidBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.proto.types.TxID tid = 1;</code>
       */
      public proto.types.transaction.TxID.Builder getTidBuilder() {
        
        onChanged();
        return getTidFieldBuilder().getBuilder();
      }
      /**
       * <code>.proto.types.TxID tid = 1;</code>
       */
      public proto.types.transaction.TxIDOrBuilder getTidOrBuilder() {
        if (tidBuilder_ != null) {
          return tidBuilder_.getMessageOrBuilder();
        } else {
          return tid_ == null ?
              proto.types.transaction.TxID.getDefaultInstance() : tid_;
        }
      }
      /**
       * <code>.proto.types.TxID tid = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          proto.types.transaction.TxID, proto.types.transaction.TxID.Builder, proto.types.transaction.TxIDOrBuilder> 
          getTidFieldBuilder() {
        if (tidBuilder_ == null) {
          tidBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              proto.types.transaction.TxID, proto.types.transaction.TxID.Builder, proto.types.transaction.TxIDOrBuilder>(
                  getTid(),
                  getParentForChildren(),
                  isClean());
          tid_ = null;
        }
        return tidBuilder_;
      }

      private proto.types.transaction.Transaction tx_;
      private com.google.protobuf.SingleFieldBuilderV3<
          proto.types.transaction.Transaction, proto.types.transaction.Transaction.Builder, proto.types.transaction.TransactionOrBuilder> txBuilder_;
      /**
       * <code>.proto.types.Transaction tx = 2;</code>
       */
      public boolean hasTx() {
        return txBuilder_ != null || tx_ != null;
      }
      /**
       * <code>.proto.types.Transaction tx = 2;</code>
       */
      public proto.types.transaction.Transaction getTx() {
        if (txBuilder_ == null) {
          return tx_ == null ? proto.types.transaction.Transaction.getDefaultInstance() : tx_;
        } else {
          return txBuilder_.getMessage();
        }
      }
      /**
       * <code>.proto.types.Transaction tx = 2;</code>
       */
      public Builder setTx(proto.types.transaction.Transaction value) {
        if (txBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          tx_ = value;
          onChanged();
        } else {
          txBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.proto.types.Transaction tx = 2;</code>
       */
      public Builder setTx(
          proto.types.transaction.Transaction.Builder builderForValue) {
        if (txBuilder_ == null) {
          tx_ = builderForValue.build();
          onChanged();
        } else {
          txBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.proto.types.Transaction tx = 2;</code>
       */
      public Builder mergeTx(proto.types.transaction.Transaction value) {
        if (txBuilder_ == null) {
          if (tx_ != null) {
            tx_ =
              proto.types.transaction.Transaction.newBuilder(tx_).mergeFrom(value).buildPartial();
          } else {
            tx_ = value;
          }
          onChanged();
        } else {
          txBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.proto.types.Transaction tx = 2;</code>
       */
      public Builder clearTx() {
        if (txBuilder_ == null) {
          tx_ = null;
          onChanged();
        } else {
          tx_ = null;
          txBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.proto.types.Transaction tx = 2;</code>
       */
      public proto.types.transaction.Transaction.Builder getTxBuilder() {
        
        onChanged();
        return getTxFieldBuilder().getBuilder();
      }
      /**
       * <code>.proto.types.Transaction tx = 2;</code>
       */
      public proto.types.transaction.TransactionOrBuilder getTxOrBuilder() {
        if (txBuilder_ != null) {
          return txBuilder_.getMessageOrBuilder();
        } else {
          return tx_ == null ?
              proto.types.transaction.Transaction.getDefaultInstance() : tx_;
        }
      }
      /**
       * <code>.proto.types.Transaction tx = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          proto.types.transaction.Transaction, proto.types.transaction.Transaction.Builder, proto.types.transaction.TransactionOrBuilder> 
          getTxFieldBuilder() {
        if (txBuilder_ == null) {
          txBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              proto.types.transaction.Transaction, proto.types.transaction.Transaction.Builder, proto.types.transaction.TransactionOrBuilder>(
                  getTx(),
                  getParentForChildren(),
                  isClean());
          tx_ = null;
        }
        return txBuilder_;
      }

      private boolean blocking_ ;
      /**
       * <code>bool blocking = 3;</code>
       */
      public boolean getBlocking() {
        return blocking_;
      }
      /**
       * <code>bool blocking = 3;</code>
       */
      public Builder setBlocking(boolean value) {
        
        blocking_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool blocking = 3;</code>
       */
      public Builder clearBlocking() {
        
        blocking_ = false;
        onChanged();
        return this;
      }

      private int cid_ ;
      /**
       * <code>int32 cid = 4;</code>
       */
      public int getCid() {
        return cid_;
      }
      /**
       * <code>int32 cid = 4;</code>
       */
      public Builder setCid(int value) {
        
        cid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 cid = 4;</code>
       */
      public Builder clearCid() {
        
        cid_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto.types.ReadReq)
    }

    // @@protoc_insertion_point(class_scope:proto.types.ReadReq)
    private static final proto.types.client.ReadReq DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto.types.client.ReadReq();
    }

    public static proto.types.client.ReadReq getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ReadReq>
        PARSER = new com.google.protobuf.AbstractParser<ReadReq>() {
      @java.lang.Override
      public ReadReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ReadReq(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ReadReq> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ReadReq> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public proto.types.client.ReadReq getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TxStatusOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.types.TxStatus)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 res = 1;</code>
     */
    int getRes();
  }
  /**
   * Protobuf type {@code proto.types.TxStatus}
   */
  public  static final class TxStatus extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.types.TxStatus)
      TxStatusOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TxStatus.newBuilder() to construct.
    private TxStatus(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TxStatus() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TxStatus(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              res_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.types.client.internal_static_proto_types_TxStatus_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.types.client.internal_static_proto_types_TxStatus_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.types.client.TxStatus.class, proto.types.client.TxStatus.Builder.class);
    }

    public static final int RES_FIELD_NUMBER = 1;
    private int res_;
    /**
     * <code>int32 res = 1;</code>
     */
    public int getRes() {
      return res_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (res_ != 0) {
        output.writeInt32(1, res_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (res_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, res_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto.types.client.TxStatus)) {
        return super.equals(obj);
      }
      proto.types.client.TxStatus other = (proto.types.client.TxStatus) obj;

      if (getRes()
          != other.getRes()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RES_FIELD_NUMBER;
      hash = (53 * hash) + getRes();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto.types.client.TxStatus parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.types.client.TxStatus parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.types.client.TxStatus parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.types.client.TxStatus parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.types.client.TxStatus parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.types.client.TxStatus parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.types.client.TxStatus parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.types.client.TxStatus parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.types.client.TxStatus parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static proto.types.client.TxStatus parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.types.client.TxStatus parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.types.client.TxStatus parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto.types.client.TxStatus prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.types.TxStatus}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.types.TxStatus)
        proto.types.client.TxStatusOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.types.client.internal_static_proto_types_TxStatus_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.types.client.internal_static_proto_types_TxStatus_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.types.client.TxStatus.class, proto.types.client.TxStatus.Builder.class);
      }

      // Construct using proto.types.client.TxStatus.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        res_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.types.client.internal_static_proto_types_TxStatus_descriptor;
      }

      @java.lang.Override
      public proto.types.client.TxStatus getDefaultInstanceForType() {
        return proto.types.client.TxStatus.getDefaultInstance();
      }

      @java.lang.Override
      public proto.types.client.TxStatus build() {
        proto.types.client.TxStatus result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public proto.types.client.TxStatus buildPartial() {
        proto.types.client.TxStatus result = new proto.types.client.TxStatus(this);
        result.res_ = res_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.types.client.TxStatus) {
          return mergeFrom((proto.types.client.TxStatus)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.types.client.TxStatus other) {
        if (other == proto.types.client.TxStatus.getDefaultInstance()) return this;
        if (other.getRes() != 0) {
          setRes(other.getRes());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.types.client.TxStatus parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.types.client.TxStatus) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int res_ ;
      /**
       * <code>int32 res = 1;</code>
       */
      public int getRes() {
        return res_;
      }
      /**
       * <code>int32 res = 1;</code>
       */
      public Builder setRes(int value) {
        
        res_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 res = 1;</code>
       */
      public Builder clearRes() {
        
        res_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto.types.TxStatus)
    }

    // @@protoc_insertion_point(class_scope:proto.types.TxStatus)
    private static final proto.types.client.TxStatus DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto.types.client.TxStatus();
    }

    public static proto.types.client.TxStatus getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TxStatus>
        PARSER = new com.google.protobuf.AbstractParser<TxStatus>() {
      @java.lang.Override
      public TxStatus parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TxStatus(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TxStatus> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TxStatus> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public proto.types.client.TxStatus getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_types_Accepted_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_types_Accepted_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_types_ReadReq_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_types_ReadReq_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_types_TxStatus_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_types_TxStatus_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022types/client.proto\022\013proto.types\032\027types" +
      "/transaction.proto\"=\n\010Accepted\022\020\n\010accept" +
      "ed\030\001 \001(\010\022\037\n\004txID\030\002 \001(\0132\021.proto.types.TxI" +
      "D\"n\n\007ReadReq\022\036\n\003tid\030\001 \001(\0132\021.proto.types." +
      "TxID\022$\n\002tx\030\002 \001(\0132\030.proto.types.Transacti" +
      "on\022\020\n\010blocking\030\003 \001(\010\022\013\n\003cid\030\004 \001(\005\"\027\n\010TxS" +
      "tatus\022\013\n\003res\030\001 \001(\005B\025\n\013proto.typesB\006clien" +
      "tb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          proto.types.transaction.getDescriptor(),
        }, assigner);
    internal_static_proto_types_Accepted_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_types_Accepted_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_types_Accepted_descriptor,
        new java.lang.String[] { "Accepted", "TxID", });
    internal_static_proto_types_ReadReq_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_proto_types_ReadReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_types_ReadReq_descriptor,
        new java.lang.String[] { "Tid", "Tx", "Blocking", "Cid", });
    internal_static_proto_types_TxStatus_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_proto_types_TxStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_types_TxStatus_descriptor,
        new java.lang.String[] { "Res", });
    proto.types.transaction.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
