// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: types/forkproof.proto

package proto.types;

public final class forkproof {
  private forkproof() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ForkProofOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.types.ForkProof)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 sender = 1;</code>
     */
    int getSender();

    /**
     * <code>.proto.types.Block curr = 2;</code>
     */
    boolean hasCurr();
    /**
     * <code>.proto.types.Block curr = 2;</code>
     */
    proto.types.block.Block getCurr();
    /**
     * <code>.proto.types.Block curr = 2;</code>
     */
    proto.types.block.BlockOrBuilder getCurrOrBuilder();

    /**
     * <pre>
     *    bool done = 4;
     * </pre>
     *
     * <code>.proto.types.Block prev = 3;</code>
     */
    boolean hasPrev();
    /**
     * <pre>
     *    bool done = 4;
     * </pre>
     *
     * <code>.proto.types.Block prev = 3;</code>
     */
    proto.types.block.Block getPrev();
    /**
     * <pre>
     *    bool done = 4;
     * </pre>
     *
     * <code>.proto.types.Block prev = 3;</code>
     */
    proto.types.block.BlockOrBuilder getPrevOrBuilder();
  }
  /**
   * Protobuf type {@code proto.types.ForkProof}
   */
  public  static final class ForkProof extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.types.ForkProof)
      ForkProofOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ForkProof.newBuilder() to construct.
    private ForkProof(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ForkProof() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ForkProof(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              sender_ = input.readInt32();
              break;
            }
            case 18: {
              proto.types.block.Block.Builder subBuilder = null;
              if (curr_ != null) {
                subBuilder = curr_.toBuilder();
              }
              curr_ = input.readMessage(proto.types.block.Block.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(curr_);
                curr_ = subBuilder.buildPartial();
              }

              break;
            }
            case 26: {
              proto.types.block.Block.Builder subBuilder = null;
              if (prev_ != null) {
                subBuilder = prev_.toBuilder();
              }
              prev_ = input.readMessage(proto.types.block.Block.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(prev_);
                prev_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.types.forkproof.internal_static_proto_types_ForkProof_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.types.forkproof.internal_static_proto_types_ForkProof_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.types.forkproof.ForkProof.class, proto.types.forkproof.ForkProof.Builder.class);
    }

    public static final int SENDER_FIELD_NUMBER = 1;
    private int sender_;
    /**
     * <code>int32 sender = 1;</code>
     */
    public int getSender() {
      return sender_;
    }

    public static final int CURR_FIELD_NUMBER = 2;
    private proto.types.block.Block curr_;
    /**
     * <code>.proto.types.Block curr = 2;</code>
     */
    public boolean hasCurr() {
      return curr_ != null;
    }
    /**
     * <code>.proto.types.Block curr = 2;</code>
     */
    public proto.types.block.Block getCurr() {
      return curr_ == null ? proto.types.block.Block.getDefaultInstance() : curr_;
    }
    /**
     * <code>.proto.types.Block curr = 2;</code>
     */
    public proto.types.block.BlockOrBuilder getCurrOrBuilder() {
      return getCurr();
    }

    public static final int PREV_FIELD_NUMBER = 3;
    private proto.types.block.Block prev_;
    /**
     * <pre>
     *    bool done = 4;
     * </pre>
     *
     * <code>.proto.types.Block prev = 3;</code>
     */
    public boolean hasPrev() {
      return prev_ != null;
    }
    /**
     * <pre>
     *    bool done = 4;
     * </pre>
     *
     * <code>.proto.types.Block prev = 3;</code>
     */
    public proto.types.block.Block getPrev() {
      return prev_ == null ? proto.types.block.Block.getDefaultInstance() : prev_;
    }
    /**
     * <pre>
     *    bool done = 4;
     * </pre>
     *
     * <code>.proto.types.Block prev = 3;</code>
     */
    public proto.types.block.BlockOrBuilder getPrevOrBuilder() {
      return getPrev();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (sender_ != 0) {
        output.writeInt32(1, sender_);
      }
      if (curr_ != null) {
        output.writeMessage(2, getCurr());
      }
      if (prev_ != null) {
        output.writeMessage(3, getPrev());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (sender_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, sender_);
      }
      if (curr_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getCurr());
      }
      if (prev_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getPrev());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto.types.forkproof.ForkProof)) {
        return super.equals(obj);
      }
      proto.types.forkproof.ForkProof other = (proto.types.forkproof.ForkProof) obj;

      if (getSender()
          != other.getSender()) return false;
      if (hasCurr() != other.hasCurr()) return false;
      if (hasCurr()) {
        if (!getCurr()
            .equals(other.getCurr())) return false;
      }
      if (hasPrev() != other.hasPrev()) return false;
      if (hasPrev()) {
        if (!getPrev()
            .equals(other.getPrev())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SENDER_FIELD_NUMBER;
      hash = (53 * hash) + getSender();
      if (hasCurr()) {
        hash = (37 * hash) + CURR_FIELD_NUMBER;
        hash = (53 * hash) + getCurr().hashCode();
      }
      if (hasPrev()) {
        hash = (37 * hash) + PREV_FIELD_NUMBER;
        hash = (53 * hash) + getPrev().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto.types.forkproof.ForkProof parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.types.forkproof.ForkProof parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.types.forkproof.ForkProof parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.types.forkproof.ForkProof parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.types.forkproof.ForkProof parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.types.forkproof.ForkProof parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.types.forkproof.ForkProof parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.types.forkproof.ForkProof parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.types.forkproof.ForkProof parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static proto.types.forkproof.ForkProof parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.types.forkproof.ForkProof parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.types.forkproof.ForkProof parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto.types.forkproof.ForkProof prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.types.ForkProof}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.types.ForkProof)
        proto.types.forkproof.ForkProofOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.types.forkproof.internal_static_proto_types_ForkProof_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.types.forkproof.internal_static_proto_types_ForkProof_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.types.forkproof.ForkProof.class, proto.types.forkproof.ForkProof.Builder.class);
      }

      // Construct using proto.types.forkproof.ForkProof.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        sender_ = 0;

        if (currBuilder_ == null) {
          curr_ = null;
        } else {
          curr_ = null;
          currBuilder_ = null;
        }
        if (prevBuilder_ == null) {
          prev_ = null;
        } else {
          prev_ = null;
          prevBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.types.forkproof.internal_static_proto_types_ForkProof_descriptor;
      }

      @java.lang.Override
      public proto.types.forkproof.ForkProof getDefaultInstanceForType() {
        return proto.types.forkproof.ForkProof.getDefaultInstance();
      }

      @java.lang.Override
      public proto.types.forkproof.ForkProof build() {
        proto.types.forkproof.ForkProof result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public proto.types.forkproof.ForkProof buildPartial() {
        proto.types.forkproof.ForkProof result = new proto.types.forkproof.ForkProof(this);
        result.sender_ = sender_;
        if (currBuilder_ == null) {
          result.curr_ = curr_;
        } else {
          result.curr_ = currBuilder_.build();
        }
        if (prevBuilder_ == null) {
          result.prev_ = prev_;
        } else {
          result.prev_ = prevBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.types.forkproof.ForkProof) {
          return mergeFrom((proto.types.forkproof.ForkProof)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.types.forkproof.ForkProof other) {
        if (other == proto.types.forkproof.ForkProof.getDefaultInstance()) return this;
        if (other.getSender() != 0) {
          setSender(other.getSender());
        }
        if (other.hasCurr()) {
          mergeCurr(other.getCurr());
        }
        if (other.hasPrev()) {
          mergePrev(other.getPrev());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.types.forkproof.ForkProof parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.types.forkproof.ForkProof) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int sender_ ;
      /**
       * <code>int32 sender = 1;</code>
       */
      public int getSender() {
        return sender_;
      }
      /**
       * <code>int32 sender = 1;</code>
       */
      public Builder setSender(int value) {
        
        sender_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 sender = 1;</code>
       */
      public Builder clearSender() {
        
        sender_ = 0;
        onChanged();
        return this;
      }

      private proto.types.block.Block curr_;
      private com.google.protobuf.SingleFieldBuilderV3<
          proto.types.block.Block, proto.types.block.Block.Builder, proto.types.block.BlockOrBuilder> currBuilder_;
      /**
       * <code>.proto.types.Block curr = 2;</code>
       */
      public boolean hasCurr() {
        return currBuilder_ != null || curr_ != null;
      }
      /**
       * <code>.proto.types.Block curr = 2;</code>
       */
      public proto.types.block.Block getCurr() {
        if (currBuilder_ == null) {
          return curr_ == null ? proto.types.block.Block.getDefaultInstance() : curr_;
        } else {
          return currBuilder_.getMessage();
        }
      }
      /**
       * <code>.proto.types.Block curr = 2;</code>
       */
      public Builder setCurr(proto.types.block.Block value) {
        if (currBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          curr_ = value;
          onChanged();
        } else {
          currBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.proto.types.Block curr = 2;</code>
       */
      public Builder setCurr(
          proto.types.block.Block.Builder builderForValue) {
        if (currBuilder_ == null) {
          curr_ = builderForValue.build();
          onChanged();
        } else {
          currBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.proto.types.Block curr = 2;</code>
       */
      public Builder mergeCurr(proto.types.block.Block value) {
        if (currBuilder_ == null) {
          if (curr_ != null) {
            curr_ =
              proto.types.block.Block.newBuilder(curr_).mergeFrom(value).buildPartial();
          } else {
            curr_ = value;
          }
          onChanged();
        } else {
          currBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.proto.types.Block curr = 2;</code>
       */
      public Builder clearCurr() {
        if (currBuilder_ == null) {
          curr_ = null;
          onChanged();
        } else {
          curr_ = null;
          currBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.proto.types.Block curr = 2;</code>
       */
      public proto.types.block.Block.Builder getCurrBuilder() {
        
        onChanged();
        return getCurrFieldBuilder().getBuilder();
      }
      /**
       * <code>.proto.types.Block curr = 2;</code>
       */
      public proto.types.block.BlockOrBuilder getCurrOrBuilder() {
        if (currBuilder_ != null) {
          return currBuilder_.getMessageOrBuilder();
        } else {
          return curr_ == null ?
              proto.types.block.Block.getDefaultInstance() : curr_;
        }
      }
      /**
       * <code>.proto.types.Block curr = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          proto.types.block.Block, proto.types.block.Block.Builder, proto.types.block.BlockOrBuilder> 
          getCurrFieldBuilder() {
        if (currBuilder_ == null) {
          currBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              proto.types.block.Block, proto.types.block.Block.Builder, proto.types.block.BlockOrBuilder>(
                  getCurr(),
                  getParentForChildren(),
                  isClean());
          curr_ = null;
        }
        return currBuilder_;
      }

      private proto.types.block.Block prev_;
      private com.google.protobuf.SingleFieldBuilderV3<
          proto.types.block.Block, proto.types.block.Block.Builder, proto.types.block.BlockOrBuilder> prevBuilder_;
      /**
       * <pre>
       *    bool done = 4;
       * </pre>
       *
       * <code>.proto.types.Block prev = 3;</code>
       */
      public boolean hasPrev() {
        return prevBuilder_ != null || prev_ != null;
      }
      /**
       * <pre>
       *    bool done = 4;
       * </pre>
       *
       * <code>.proto.types.Block prev = 3;</code>
       */
      public proto.types.block.Block getPrev() {
        if (prevBuilder_ == null) {
          return prev_ == null ? proto.types.block.Block.getDefaultInstance() : prev_;
        } else {
          return prevBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       *    bool done = 4;
       * </pre>
       *
       * <code>.proto.types.Block prev = 3;</code>
       */
      public Builder setPrev(proto.types.block.Block value) {
        if (prevBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          prev_ = value;
          onChanged();
        } else {
          prevBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       *    bool done = 4;
       * </pre>
       *
       * <code>.proto.types.Block prev = 3;</code>
       */
      public Builder setPrev(
          proto.types.block.Block.Builder builderForValue) {
        if (prevBuilder_ == null) {
          prev_ = builderForValue.build();
          onChanged();
        } else {
          prevBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       *    bool done = 4;
       * </pre>
       *
       * <code>.proto.types.Block prev = 3;</code>
       */
      public Builder mergePrev(proto.types.block.Block value) {
        if (prevBuilder_ == null) {
          if (prev_ != null) {
            prev_ =
              proto.types.block.Block.newBuilder(prev_).mergeFrom(value).buildPartial();
          } else {
            prev_ = value;
          }
          onChanged();
        } else {
          prevBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       *    bool done = 4;
       * </pre>
       *
       * <code>.proto.types.Block prev = 3;</code>
       */
      public Builder clearPrev() {
        if (prevBuilder_ == null) {
          prev_ = null;
          onChanged();
        } else {
          prev_ = null;
          prevBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       *    bool done = 4;
       * </pre>
       *
       * <code>.proto.types.Block prev = 3;</code>
       */
      public proto.types.block.Block.Builder getPrevBuilder() {
        
        onChanged();
        return getPrevFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       *    bool done = 4;
       * </pre>
       *
       * <code>.proto.types.Block prev = 3;</code>
       */
      public proto.types.block.BlockOrBuilder getPrevOrBuilder() {
        if (prevBuilder_ != null) {
          return prevBuilder_.getMessageOrBuilder();
        } else {
          return prev_ == null ?
              proto.types.block.Block.getDefaultInstance() : prev_;
        }
      }
      /**
       * <pre>
       *    bool done = 4;
       * </pre>
       *
       * <code>.proto.types.Block prev = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          proto.types.block.Block, proto.types.block.Block.Builder, proto.types.block.BlockOrBuilder> 
          getPrevFieldBuilder() {
        if (prevBuilder_ == null) {
          prevBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              proto.types.block.Block, proto.types.block.Block.Builder, proto.types.block.BlockOrBuilder>(
                  getPrev(),
                  getParentForChildren(),
                  isClean());
          prev_ = null;
        }
        return prevBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto.types.ForkProof)
    }

    // @@protoc_insertion_point(class_scope:proto.types.ForkProof)
    private static final proto.types.forkproof.ForkProof DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto.types.forkproof.ForkProof();
    }

    public static proto.types.forkproof.ForkProof getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ForkProof>
        PARSER = new com.google.protobuf.AbstractParser<ForkProof>() {
      @java.lang.Override
      public ForkProof parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ForkProof(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ForkProof> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ForkProof> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public proto.types.forkproof.ForkProof getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_types_ForkProof_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_types_ForkProof_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025types/forkproof.proto\022\013proto.types\032\021ty" +
      "pes/block.proto\"_\n\tForkProof\022\016\n\006sender\030\001" +
      " \001(\005\022 \n\004curr\030\002 \001(\0132\022.proto.types.Block\022 " +
      "\n\004prev\030\003 \001(\0132\022.proto.types.BlockB\030\n\013prot" +
      "o.typesB\tforkproofb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          proto.types.block.getDescriptor(),
        }, assigner);
    internal_static_proto_types_ForkProof_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_types_ForkProof_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_types_ForkProof_descriptor,
        new java.lang.String[] { "Sender", "Curr", "Prev", });
    proto.types.block.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
