version: "2.1"
services:
   TS0:
        image: toy:0.1
        container_name: TS_0
        environment:
        - ID=0
        - Type=r
        volumes:
        - /home/yoni/Desktop/dtoy/curr/:/tmp/JToy
        - /home/yoni/Desktop/dtoy/configurations/fbenign:/JToy/bin/src/main/resources
        networks:
            composed_toy_net:
                ipv4_address: 172.18.0.3
   TS1:
        image: toy:0.1
        container_name: TS_1
        environment:
        - ID=1
        - Type=r
        volumes:
        - /home/yoni/Desktop/dtoy/curr/:/tmp/JToy
        - /home/yoni/Desktop/dtoy/configurations/correct:/JToy/bin/src/main/resources
        networks:
            composed_toy_net:
                ipv4_address: 172.18.0.4
   TS2:
        image: toy:0.1
        container_name: TS_2
        environment:
        - ID=2
        - Type=r
        volumes:
        - /home/yoni/Desktop/dtoy/curr/:/tmp/JToy
        - /home/yoni/Desktop/dtoy/configurations/correct:/JToy/bin/src/main/resources
        networks:
            composed_toy_net:
                ipv4_address: 172.18.0.5
   TS3:
        image: toy:0.1
        container_name: TS_3
        environment:
        - ID=3
        - Type=r
        volumes:
        - /home/yoni/Desktop/dtoy/curr/:/tmp/JToy
        - /home/yoni/Desktop/dtoy/configurations/correct:/JToy/bin/src/main/resources
        networks:
            composed_toy_net:
                ipv4_address: 172.18.0.6
networks:
    composed_toy_net:
        driver: bridge
        external: true
        ipam:
            driver: default
            config:
            - subnet: 172.18.0.0/16
              gateway: 172.18.0.1
