version: "2.1"
services:
   TS0:
        image: toy:0.1
        container_name: TS_0
        environment:
        - ID=0
        - Type=r
        volumes:
        - /home/yoni/Desktop/dtoy/curr/:/tmp/JToy
        - /home/yoni/Desktop/dtoy/configurations/benign:/JToy/bin/src/main/resources
        networks:
            toy_net:
                ipv4_address: 172.18.0.3
networks:
    toy_net:
        driver: bridge
        ipam:
            driver: default
            config:
            - subnet: 172.18.0.0/16
              gateway: 172.18.0.1
