version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: jtoy:0.1
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    networks:
      - webnet
networks:
  webnet: