// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: blockchain.proto

package proto;

public interface BlockOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.Block)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 creatorID = 1;</code>
   */
  int getCreatorID();

  /**
   * <code>int32 height = 2;</code>
   */
  int getHeight();

  /**
   * <pre>
   * Currently an index only
   * </pre>
   *
   * <code>int32 prevHash = 3;</code>
   */
  int getPrevHash();

  /**
   * <code>repeated .proto.Transaction data = 4;</code>
   */
  java.util.List<proto.Transaction> 
      getDataList();
  /**
   * <code>repeated .proto.Transaction data = 4;</code>
   */
  proto.Transaction getData(int index);
  /**
   * <code>repeated .proto.Transaction data = 4;</code>
   */
  int getDataCount();
  /**
   * <code>repeated .proto.Transaction data = 4;</code>
   */
  java.util.List<? extends proto.TransactionOrBuilder> 
      getDataOrBuilderList();
  /**
   * <code>repeated .proto.Transaction data = 4;</code>
   */
  proto.TransactionOrBuilder getDataOrBuilder(
      int index);
}
