// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rmfService.proto

package proto;

public interface FastBbcVoteOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.FastBbcVote)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 sender = 1;</code>
   */
  int getSender();

  /**
   * <code>int32 vote = 2;</code>
   */
  int getVote();

  /**
   * <code>int32 cid = 3;</code>
   */
  int getCid();

  /**
   * <code>string sig = 4;</code>
   */
  java.lang.String getSig();
  /**
   * <code>string sig = 4;</code>
   */
  com.google.protobuf.ByteString
      getSigBytes();
}
