// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: syncService.proto

package proto;

public interface frontSupportOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.frontSupport)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 sid = 1;</code>
   */
  int getSid();

  /**
   * <code>int32 id = 2;</code>
   */
  int getId();

  /**
   * <code>int32 height = 3;</code>
   */
  int getHeight();

  /**
   * <code>string sig = 4;</code>
   */
  java.lang.String getSig();
  /**
   * <code>string sig = 4;</code>
   */
  com.google.protobuf.ByteString
      getSigBytes();
}
