// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rmfService.proto

package proto;

public final class RmfProtos {
  private RmfProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface EmptyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.Empty)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code proto.Empty}
   */
  public  static final class Empty extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.Empty)
      EmptyOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Empty.newBuilder() to construct.
    private Empty(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Empty() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Empty(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.RmfProtos.internal_static_proto_Empty_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.RmfProtos.internal_static_proto_Empty_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.RmfProtos.Empty.class, proto.RmfProtos.Empty.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto.RmfProtos.Empty)) {
        return super.equals(obj);
      }
      proto.RmfProtos.Empty other = (proto.RmfProtos.Empty) obj;

      boolean result = true;
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto.RmfProtos.Empty parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.RmfProtos.Empty parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.RmfProtos.Empty parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.RmfProtos.Empty parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.RmfProtos.Empty parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.RmfProtos.Empty parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.RmfProtos.Empty parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.RmfProtos.Empty parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.RmfProtos.Empty parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static proto.RmfProtos.Empty parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.RmfProtos.Empty parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.RmfProtos.Empty parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto.RmfProtos.Empty prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.Empty}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.Empty)
        proto.RmfProtos.EmptyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.RmfProtos.internal_static_proto_Empty_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.RmfProtos.internal_static_proto_Empty_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.RmfProtos.Empty.class, proto.RmfProtos.Empty.Builder.class);
      }

      // Construct using proto.RmfProtos.Empty.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.RmfProtos.internal_static_proto_Empty_descriptor;
      }

      public proto.RmfProtos.Empty getDefaultInstanceForType() {
        return proto.RmfProtos.Empty.getDefaultInstance();
      }

      public proto.RmfProtos.Empty build() {
        proto.RmfProtos.Empty result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public proto.RmfProtos.Empty buildPartial() {
        proto.RmfProtos.Empty result = new proto.RmfProtos.Empty(this);
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.RmfProtos.Empty) {
          return mergeFrom((proto.RmfProtos.Empty)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.RmfProtos.Empty other) {
        if (other == proto.RmfProtos.Empty.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.RmfProtos.Empty parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.RmfProtos.Empty) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto.Empty)
    }

    // @@protoc_insertion_point(class_scope:proto.Empty)
    private static final proto.RmfProtos.Empty DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto.RmfProtos.Empty();
    }

    public static proto.RmfProtos.Empty getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Empty>
        PARSER = new com.google.protobuf.AbstractParser<Empty>() {
      public Empty parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Empty(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Empty> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Empty> getParserForType() {
      return PARSER;
    }

    public proto.RmfProtos.Empty getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MetaOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.Meta)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 sender = 1;</code>
     */
    int getSender();

    /**
     * <code>int32 height = 2;</code>
     */
    int getHeight();
  }
  /**
   * Protobuf type {@code proto.Meta}
   */
  public  static final class Meta extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.Meta)
      MetaOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Meta.newBuilder() to construct.
    private Meta(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Meta() {
      sender_ = 0;
      height_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Meta(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              sender_ = input.readInt32();
              break;
            }
            case 16: {

              height_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.RmfProtos.internal_static_proto_Meta_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.RmfProtos.internal_static_proto_Meta_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.RmfProtos.Meta.class, proto.RmfProtos.Meta.Builder.class);
    }

    public static final int SENDER_FIELD_NUMBER = 1;
    private int sender_;
    /**
     * <code>int32 sender = 1;</code>
     */
    public int getSender() {
      return sender_;
    }

    public static final int HEIGHT_FIELD_NUMBER = 2;
    private int height_;
    /**
     * <code>int32 height = 2;</code>
     */
    public int getHeight() {
      return height_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (sender_ != 0) {
        output.writeInt32(1, sender_);
      }
      if (height_ != 0) {
        output.writeInt32(2, height_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (sender_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, sender_);
      }
      if (height_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, height_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto.RmfProtos.Meta)) {
        return super.equals(obj);
      }
      proto.RmfProtos.Meta other = (proto.RmfProtos.Meta) obj;

      boolean result = true;
      result = result && (getSender()
          == other.getSender());
      result = result && (getHeight()
          == other.getHeight());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SENDER_FIELD_NUMBER;
      hash = (53 * hash) + getSender();
      hash = (37 * hash) + HEIGHT_FIELD_NUMBER;
      hash = (53 * hash) + getHeight();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto.RmfProtos.Meta parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.RmfProtos.Meta parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.RmfProtos.Meta parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.RmfProtos.Meta parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.RmfProtos.Meta parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.RmfProtos.Meta parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.RmfProtos.Meta parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.RmfProtos.Meta parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.RmfProtos.Meta parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static proto.RmfProtos.Meta parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.RmfProtos.Meta parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.RmfProtos.Meta parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto.RmfProtos.Meta prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.Meta}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.Meta)
        proto.RmfProtos.MetaOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.RmfProtos.internal_static_proto_Meta_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.RmfProtos.internal_static_proto_Meta_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.RmfProtos.Meta.class, proto.RmfProtos.Meta.Builder.class);
      }

      // Construct using proto.RmfProtos.Meta.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        sender_ = 0;

        height_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.RmfProtos.internal_static_proto_Meta_descriptor;
      }

      public proto.RmfProtos.Meta getDefaultInstanceForType() {
        return proto.RmfProtos.Meta.getDefaultInstance();
      }

      public proto.RmfProtos.Meta build() {
        proto.RmfProtos.Meta result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public proto.RmfProtos.Meta buildPartial() {
        proto.RmfProtos.Meta result = new proto.RmfProtos.Meta(this);
        result.sender_ = sender_;
        result.height_ = height_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.RmfProtos.Meta) {
          return mergeFrom((proto.RmfProtos.Meta)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.RmfProtos.Meta other) {
        if (other == proto.RmfProtos.Meta.getDefaultInstance()) return this;
        if (other.getSender() != 0) {
          setSender(other.getSender());
        }
        if (other.getHeight() != 0) {
          setHeight(other.getHeight());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.RmfProtos.Meta parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.RmfProtos.Meta) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int sender_ ;
      /**
       * <code>int32 sender = 1;</code>
       */
      public int getSender() {
        return sender_;
      }
      /**
       * <code>int32 sender = 1;</code>
       */
      public Builder setSender(int value) {
        
        sender_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 sender = 1;</code>
       */
      public Builder clearSender() {
        
        sender_ = 0;
        onChanged();
        return this;
      }

      private int height_ ;
      /**
       * <code>int32 height = 2;</code>
       */
      public int getHeight() {
        return height_;
      }
      /**
       * <code>int32 height = 2;</code>
       */
      public Builder setHeight(int value) {
        
        height_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 height = 2;</code>
       */
      public Builder clearHeight() {
        
        height_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto.Meta)
    }

    // @@protoc_insertion_point(class_scope:proto.Meta)
    private static final proto.RmfProtos.Meta DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto.RmfProtos.Meta();
    }

    public static proto.RmfProtos.Meta getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Meta>
        PARSER = new com.google.protobuf.AbstractParser<Meta>() {
      public Meta parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Meta(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Meta> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Meta> getParserForType() {
      return PARSER;
    }

    public proto.RmfProtos.Meta getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface DataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.Data)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.proto.Meta _meta = 1;</code>
     */
    boolean hasMeta();
    /**
     * <code>.proto.Meta _meta = 1;</code>
     */
    proto.RmfProtos.Meta getMeta();
    /**
     * <code>.proto.Meta _meta = 1;</code>
     */
    proto.RmfProtos.MetaOrBuilder getMetaOrBuilder();

    /**
     * <code>bytes data = 2;</code>
     */
    com.google.protobuf.ByteString getData();
  }
  /**
   * Protobuf type {@code proto.Data}
   */
  public  static final class Data extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.Data)
      DataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Data.newBuilder() to construct.
    private Data(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Data() {
      data_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Data(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              proto.RmfProtos.Meta.Builder subBuilder = null;
              if (Meta_ != null) {
                subBuilder = Meta_.toBuilder();
              }
              Meta_ = input.readMessage(proto.RmfProtos.Meta.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(Meta_);
                Meta_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {

              data_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.RmfProtos.internal_static_proto_Data_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.RmfProtos.internal_static_proto_Data_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.RmfProtos.Data.class, proto.RmfProtos.Data.Builder.class);
    }

    public static final int _META_FIELD_NUMBER = 1;
    private proto.RmfProtos.Meta Meta_;
    /**
     * <code>.proto.Meta _meta = 1;</code>
     */
    public boolean hasMeta() {
      return Meta_ != null;
    }
    /**
     * <code>.proto.Meta _meta = 1;</code>
     */
    public proto.RmfProtos.Meta getMeta() {
      return Meta_ == null ? proto.RmfProtos.Meta.getDefaultInstance() : Meta_;
    }
    /**
     * <code>.proto.Meta _meta = 1;</code>
     */
    public proto.RmfProtos.MetaOrBuilder getMetaOrBuilder() {
      return getMeta();
    }

    public static final int DATA_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString data_;
    /**
     * <code>bytes data = 2;</code>
     */
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (Meta_ != null) {
        output.writeMessage(1, getMeta());
      }
      if (!data_.isEmpty()) {
        output.writeBytes(2, data_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (Meta_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getMeta());
      }
      if (!data_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, data_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto.RmfProtos.Data)) {
        return super.equals(obj);
      }
      proto.RmfProtos.Data other = (proto.RmfProtos.Data) obj;

      boolean result = true;
      result = result && (hasMeta() == other.hasMeta());
      if (hasMeta()) {
        result = result && getMeta()
            .equals(other.getMeta());
      }
      result = result && getData()
          .equals(other.getData());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasMeta()) {
        hash = (37 * hash) + _META_FIELD_NUMBER;
        hash = (53 * hash) + getMeta().hashCode();
      }
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto.RmfProtos.Data parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.RmfProtos.Data parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.RmfProtos.Data parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.RmfProtos.Data parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.RmfProtos.Data parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.RmfProtos.Data parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.RmfProtos.Data parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.RmfProtos.Data parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.RmfProtos.Data parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static proto.RmfProtos.Data parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.RmfProtos.Data parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.RmfProtos.Data parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto.RmfProtos.Data prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.Data}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.Data)
        proto.RmfProtos.DataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.RmfProtos.internal_static_proto_Data_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.RmfProtos.internal_static_proto_Data_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.RmfProtos.Data.class, proto.RmfProtos.Data.Builder.class);
      }

      // Construct using proto.RmfProtos.Data.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (MetaBuilder_ == null) {
          Meta_ = null;
        } else {
          Meta_ = null;
          MetaBuilder_ = null;
        }
        data_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.RmfProtos.internal_static_proto_Data_descriptor;
      }

      public proto.RmfProtos.Data getDefaultInstanceForType() {
        return proto.RmfProtos.Data.getDefaultInstance();
      }

      public proto.RmfProtos.Data build() {
        proto.RmfProtos.Data result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public proto.RmfProtos.Data buildPartial() {
        proto.RmfProtos.Data result = new proto.RmfProtos.Data(this);
        if (MetaBuilder_ == null) {
          result.Meta_ = Meta_;
        } else {
          result.Meta_ = MetaBuilder_.build();
        }
        result.data_ = data_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.RmfProtos.Data) {
          return mergeFrom((proto.RmfProtos.Data)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.RmfProtos.Data other) {
        if (other == proto.RmfProtos.Data.getDefaultInstance()) return this;
        if (other.hasMeta()) {
          mergeMeta(other.getMeta());
        }
        if (other.getData() != com.google.protobuf.ByteString.EMPTY) {
          setData(other.getData());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.RmfProtos.Data parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.RmfProtos.Data) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private proto.RmfProtos.Meta Meta_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          proto.RmfProtos.Meta, proto.RmfProtos.Meta.Builder, proto.RmfProtos.MetaOrBuilder> MetaBuilder_;
      /**
       * <code>.proto.Meta _meta = 1;</code>
       */
      public boolean hasMeta() {
        return MetaBuilder_ != null || Meta_ != null;
      }
      /**
       * <code>.proto.Meta _meta = 1;</code>
       */
      public proto.RmfProtos.Meta getMeta() {
        if (MetaBuilder_ == null) {
          return Meta_ == null ? proto.RmfProtos.Meta.getDefaultInstance() : Meta_;
        } else {
          return MetaBuilder_.getMessage();
        }
      }
      /**
       * <code>.proto.Meta _meta = 1;</code>
       */
      public Builder setMeta(proto.RmfProtos.Meta value) {
        if (MetaBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          Meta_ = value;
          onChanged();
        } else {
          MetaBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.proto.Meta _meta = 1;</code>
       */
      public Builder setMeta(
          proto.RmfProtos.Meta.Builder builderForValue) {
        if (MetaBuilder_ == null) {
          Meta_ = builderForValue.build();
          onChanged();
        } else {
          MetaBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.proto.Meta _meta = 1;</code>
       */
      public Builder mergeMeta(proto.RmfProtos.Meta value) {
        if (MetaBuilder_ == null) {
          if (Meta_ != null) {
            Meta_ =
              proto.RmfProtos.Meta.newBuilder(Meta_).mergeFrom(value).buildPartial();
          } else {
            Meta_ = value;
          }
          onChanged();
        } else {
          MetaBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.proto.Meta _meta = 1;</code>
       */
      public Builder clearMeta() {
        if (MetaBuilder_ == null) {
          Meta_ = null;
          onChanged();
        } else {
          Meta_ = null;
          MetaBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.proto.Meta _meta = 1;</code>
       */
      public proto.RmfProtos.Meta.Builder getMetaBuilder() {
        
        onChanged();
        return getMetaFieldBuilder().getBuilder();
      }
      /**
       * <code>.proto.Meta _meta = 1;</code>
       */
      public proto.RmfProtos.MetaOrBuilder getMetaOrBuilder() {
        if (MetaBuilder_ != null) {
          return MetaBuilder_.getMessageOrBuilder();
        } else {
          return Meta_ == null ?
              proto.RmfProtos.Meta.getDefaultInstance() : Meta_;
        }
      }
      /**
       * <code>.proto.Meta _meta = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          proto.RmfProtos.Meta, proto.RmfProtos.Meta.Builder, proto.RmfProtos.MetaOrBuilder> 
          getMetaFieldBuilder() {
        if (MetaBuilder_ == null) {
          MetaBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              proto.RmfProtos.Meta, proto.RmfProtos.Meta.Builder, proto.RmfProtos.MetaOrBuilder>(
                  getMeta(),
                  getParentForChildren(),
                  isClean());
          Meta_ = null;
        }
        return MetaBuilder_;
      }

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes data = 2;</code>
       */
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <code>bytes data = 2;</code>
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes data = 2;</code>
       */
      public Builder clearData() {
        
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto.Data)
    }

    // @@protoc_insertion_point(class_scope:proto.Data)
    private static final proto.RmfProtos.Data DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto.RmfProtos.Data();
    }

    public static proto.RmfProtos.Data getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Data>
        PARSER = new com.google.protobuf.AbstractParser<Data>() {
      public Data parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Data(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Data> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Data> getParserForType() {
      return PARSER;
    }

    public proto.RmfProtos.Data getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.Req)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.proto.Meta _meta = 1;</code>
     */
    boolean hasMeta();
    /**
     * <code>.proto.Meta _meta = 1;</code>
     */
    proto.RmfProtos.Meta getMeta();
    /**
     * <code>.proto.Meta _meta = 1;</code>
     */
    proto.RmfProtos.MetaOrBuilder getMetaOrBuilder();
  }
  /**
   * Protobuf type {@code proto.Req}
   */
  public  static final class Req extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.Req)
      ReqOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Req.newBuilder() to construct.
    private Req(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Req() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Req(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              proto.RmfProtos.Meta.Builder subBuilder = null;
              if (Meta_ != null) {
                subBuilder = Meta_.toBuilder();
              }
              Meta_ = input.readMessage(proto.RmfProtos.Meta.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(Meta_);
                Meta_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.RmfProtos.internal_static_proto_Req_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.RmfProtos.internal_static_proto_Req_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.RmfProtos.Req.class, proto.RmfProtos.Req.Builder.class);
    }

    public static final int _META_FIELD_NUMBER = 1;
    private proto.RmfProtos.Meta Meta_;
    /**
     * <code>.proto.Meta _meta = 1;</code>
     */
    public boolean hasMeta() {
      return Meta_ != null;
    }
    /**
     * <code>.proto.Meta _meta = 1;</code>
     */
    public proto.RmfProtos.Meta getMeta() {
      return Meta_ == null ? proto.RmfProtos.Meta.getDefaultInstance() : Meta_;
    }
    /**
     * <code>.proto.Meta _meta = 1;</code>
     */
    public proto.RmfProtos.MetaOrBuilder getMetaOrBuilder() {
      return getMeta();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (Meta_ != null) {
        output.writeMessage(1, getMeta());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (Meta_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getMeta());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto.RmfProtos.Req)) {
        return super.equals(obj);
      }
      proto.RmfProtos.Req other = (proto.RmfProtos.Req) obj;

      boolean result = true;
      result = result && (hasMeta() == other.hasMeta());
      if (hasMeta()) {
        result = result && getMeta()
            .equals(other.getMeta());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasMeta()) {
        hash = (37 * hash) + _META_FIELD_NUMBER;
        hash = (53 * hash) + getMeta().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto.RmfProtos.Req parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.RmfProtos.Req parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.RmfProtos.Req parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.RmfProtos.Req parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.RmfProtos.Req parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.RmfProtos.Req parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.RmfProtos.Req parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.RmfProtos.Req parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.RmfProtos.Req parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static proto.RmfProtos.Req parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.RmfProtos.Req parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.RmfProtos.Req parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto.RmfProtos.Req prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.Req}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.Req)
        proto.RmfProtos.ReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.RmfProtos.internal_static_proto_Req_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.RmfProtos.internal_static_proto_Req_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.RmfProtos.Req.class, proto.RmfProtos.Req.Builder.class);
      }

      // Construct using proto.RmfProtos.Req.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (MetaBuilder_ == null) {
          Meta_ = null;
        } else {
          Meta_ = null;
          MetaBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.RmfProtos.internal_static_proto_Req_descriptor;
      }

      public proto.RmfProtos.Req getDefaultInstanceForType() {
        return proto.RmfProtos.Req.getDefaultInstance();
      }

      public proto.RmfProtos.Req build() {
        proto.RmfProtos.Req result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public proto.RmfProtos.Req buildPartial() {
        proto.RmfProtos.Req result = new proto.RmfProtos.Req(this);
        if (MetaBuilder_ == null) {
          result.Meta_ = Meta_;
        } else {
          result.Meta_ = MetaBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.RmfProtos.Req) {
          return mergeFrom((proto.RmfProtos.Req)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.RmfProtos.Req other) {
        if (other == proto.RmfProtos.Req.getDefaultInstance()) return this;
        if (other.hasMeta()) {
          mergeMeta(other.getMeta());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.RmfProtos.Req parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.RmfProtos.Req) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private proto.RmfProtos.Meta Meta_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          proto.RmfProtos.Meta, proto.RmfProtos.Meta.Builder, proto.RmfProtos.MetaOrBuilder> MetaBuilder_;
      /**
       * <code>.proto.Meta _meta = 1;</code>
       */
      public boolean hasMeta() {
        return MetaBuilder_ != null || Meta_ != null;
      }
      /**
       * <code>.proto.Meta _meta = 1;</code>
       */
      public proto.RmfProtos.Meta getMeta() {
        if (MetaBuilder_ == null) {
          return Meta_ == null ? proto.RmfProtos.Meta.getDefaultInstance() : Meta_;
        } else {
          return MetaBuilder_.getMessage();
        }
      }
      /**
       * <code>.proto.Meta _meta = 1;</code>
       */
      public Builder setMeta(proto.RmfProtos.Meta value) {
        if (MetaBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          Meta_ = value;
          onChanged();
        } else {
          MetaBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.proto.Meta _meta = 1;</code>
       */
      public Builder setMeta(
          proto.RmfProtos.Meta.Builder builderForValue) {
        if (MetaBuilder_ == null) {
          Meta_ = builderForValue.build();
          onChanged();
        } else {
          MetaBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.proto.Meta _meta = 1;</code>
       */
      public Builder mergeMeta(proto.RmfProtos.Meta value) {
        if (MetaBuilder_ == null) {
          if (Meta_ != null) {
            Meta_ =
              proto.RmfProtos.Meta.newBuilder(Meta_).mergeFrom(value).buildPartial();
          } else {
            Meta_ = value;
          }
          onChanged();
        } else {
          MetaBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.proto.Meta _meta = 1;</code>
       */
      public Builder clearMeta() {
        if (MetaBuilder_ == null) {
          Meta_ = null;
          onChanged();
        } else {
          Meta_ = null;
          MetaBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.proto.Meta _meta = 1;</code>
       */
      public proto.RmfProtos.Meta.Builder getMetaBuilder() {
        
        onChanged();
        return getMetaFieldBuilder().getBuilder();
      }
      /**
       * <code>.proto.Meta _meta = 1;</code>
       */
      public proto.RmfProtos.MetaOrBuilder getMetaOrBuilder() {
        if (MetaBuilder_ != null) {
          return MetaBuilder_.getMessageOrBuilder();
        } else {
          return Meta_ == null ?
              proto.RmfProtos.Meta.getDefaultInstance() : Meta_;
        }
      }
      /**
       * <code>.proto.Meta _meta = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          proto.RmfProtos.Meta, proto.RmfProtos.Meta.Builder, proto.RmfProtos.MetaOrBuilder> 
          getMetaFieldBuilder() {
        if (MetaBuilder_ == null) {
          MetaBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              proto.RmfProtos.Meta, proto.RmfProtos.Meta.Builder, proto.RmfProtos.MetaOrBuilder>(
                  getMeta(),
                  getParentForChildren(),
                  isClean());
          Meta_ = null;
        }
        return MetaBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto.Req)
    }

    // @@protoc_insertion_point(class_scope:proto.Req)
    private static final proto.RmfProtos.Req DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto.RmfProtos.Req();
    }

    public static proto.RmfProtos.Req getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Req>
        PARSER = new com.google.protobuf.AbstractParser<Req>() {
      public Req parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Req(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Req> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Req> getParserForType() {
      return PARSER;
    }

    public proto.RmfProtos.Req getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ResOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.Res)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.proto.Meta _meta = 1;</code>
     */
    boolean hasMeta();
    /**
     * <code>.proto.Meta _meta = 1;</code>
     */
    proto.RmfProtos.Meta getMeta();
    /**
     * <code>.proto.Meta _meta = 1;</code>
     */
    proto.RmfProtos.MetaOrBuilder getMetaOrBuilder();

    /**
     * <code>.proto.Data _data = 2;</code>
     */
    boolean hasData();
    /**
     * <code>.proto.Data _data = 2;</code>
     */
    proto.RmfProtos.Data getData();
    /**
     * <code>.proto.Data _data = 2;</code>
     */
    proto.RmfProtos.DataOrBuilder getDataOrBuilder();
  }
  /**
   * Protobuf type {@code proto.Res}
   */
  public  static final class Res extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.Res)
      ResOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Res.newBuilder() to construct.
    private Res(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Res() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Res(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              proto.RmfProtos.Meta.Builder subBuilder = null;
              if (Meta_ != null) {
                subBuilder = Meta_.toBuilder();
              }
              Meta_ = input.readMessage(proto.RmfProtos.Meta.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(Meta_);
                Meta_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              proto.RmfProtos.Data.Builder subBuilder = null;
              if (Data_ != null) {
                subBuilder = Data_.toBuilder();
              }
              Data_ = input.readMessage(proto.RmfProtos.Data.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(Data_);
                Data_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.RmfProtos.internal_static_proto_Res_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.RmfProtos.internal_static_proto_Res_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.RmfProtos.Res.class, proto.RmfProtos.Res.Builder.class);
    }

    public static final int _META_FIELD_NUMBER = 1;
    private proto.RmfProtos.Meta Meta_;
    /**
     * <code>.proto.Meta _meta = 1;</code>
     */
    public boolean hasMeta() {
      return Meta_ != null;
    }
    /**
     * <code>.proto.Meta _meta = 1;</code>
     */
    public proto.RmfProtos.Meta getMeta() {
      return Meta_ == null ? proto.RmfProtos.Meta.getDefaultInstance() : Meta_;
    }
    /**
     * <code>.proto.Meta _meta = 1;</code>
     */
    public proto.RmfProtos.MetaOrBuilder getMetaOrBuilder() {
      return getMeta();
    }

    public static final int _DATA_FIELD_NUMBER = 2;
    private proto.RmfProtos.Data Data_;
    /**
     * <code>.proto.Data _data = 2;</code>
     */
    public boolean hasData() {
      return Data_ != null;
    }
    /**
     * <code>.proto.Data _data = 2;</code>
     */
    public proto.RmfProtos.Data getData() {
      return Data_ == null ? proto.RmfProtos.Data.getDefaultInstance() : Data_;
    }
    /**
     * <code>.proto.Data _data = 2;</code>
     */
    public proto.RmfProtos.DataOrBuilder getDataOrBuilder() {
      return getData();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (Meta_ != null) {
        output.writeMessage(1, getMeta());
      }
      if (Data_ != null) {
        output.writeMessage(2, getData());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (Meta_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getMeta());
      }
      if (Data_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getData());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto.RmfProtos.Res)) {
        return super.equals(obj);
      }
      proto.RmfProtos.Res other = (proto.RmfProtos.Res) obj;

      boolean result = true;
      result = result && (hasMeta() == other.hasMeta());
      if (hasMeta()) {
        result = result && getMeta()
            .equals(other.getMeta());
      }
      result = result && (hasData() == other.hasData());
      if (hasData()) {
        result = result && getData()
            .equals(other.getData());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasMeta()) {
        hash = (37 * hash) + _META_FIELD_NUMBER;
        hash = (53 * hash) + getMeta().hashCode();
      }
      if (hasData()) {
        hash = (37 * hash) + _DATA_FIELD_NUMBER;
        hash = (53 * hash) + getData().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto.RmfProtos.Res parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.RmfProtos.Res parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.RmfProtos.Res parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.RmfProtos.Res parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.RmfProtos.Res parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.RmfProtos.Res parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.RmfProtos.Res parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.RmfProtos.Res parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.RmfProtos.Res parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static proto.RmfProtos.Res parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.RmfProtos.Res parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.RmfProtos.Res parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto.RmfProtos.Res prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.Res}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.Res)
        proto.RmfProtos.ResOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.RmfProtos.internal_static_proto_Res_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.RmfProtos.internal_static_proto_Res_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.RmfProtos.Res.class, proto.RmfProtos.Res.Builder.class);
      }

      // Construct using proto.RmfProtos.Res.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (MetaBuilder_ == null) {
          Meta_ = null;
        } else {
          Meta_ = null;
          MetaBuilder_ = null;
        }
        if (DataBuilder_ == null) {
          Data_ = null;
        } else {
          Data_ = null;
          DataBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.RmfProtos.internal_static_proto_Res_descriptor;
      }

      public proto.RmfProtos.Res getDefaultInstanceForType() {
        return proto.RmfProtos.Res.getDefaultInstance();
      }

      public proto.RmfProtos.Res build() {
        proto.RmfProtos.Res result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public proto.RmfProtos.Res buildPartial() {
        proto.RmfProtos.Res result = new proto.RmfProtos.Res(this);
        if (MetaBuilder_ == null) {
          result.Meta_ = Meta_;
        } else {
          result.Meta_ = MetaBuilder_.build();
        }
        if (DataBuilder_ == null) {
          result.Data_ = Data_;
        } else {
          result.Data_ = DataBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.RmfProtos.Res) {
          return mergeFrom((proto.RmfProtos.Res)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.RmfProtos.Res other) {
        if (other == proto.RmfProtos.Res.getDefaultInstance()) return this;
        if (other.hasMeta()) {
          mergeMeta(other.getMeta());
        }
        if (other.hasData()) {
          mergeData(other.getData());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.RmfProtos.Res parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.RmfProtos.Res) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private proto.RmfProtos.Meta Meta_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          proto.RmfProtos.Meta, proto.RmfProtos.Meta.Builder, proto.RmfProtos.MetaOrBuilder> MetaBuilder_;
      /**
       * <code>.proto.Meta _meta = 1;</code>
       */
      public boolean hasMeta() {
        return MetaBuilder_ != null || Meta_ != null;
      }
      /**
       * <code>.proto.Meta _meta = 1;</code>
       */
      public proto.RmfProtos.Meta getMeta() {
        if (MetaBuilder_ == null) {
          return Meta_ == null ? proto.RmfProtos.Meta.getDefaultInstance() : Meta_;
        } else {
          return MetaBuilder_.getMessage();
        }
      }
      /**
       * <code>.proto.Meta _meta = 1;</code>
       */
      public Builder setMeta(proto.RmfProtos.Meta value) {
        if (MetaBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          Meta_ = value;
          onChanged();
        } else {
          MetaBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.proto.Meta _meta = 1;</code>
       */
      public Builder setMeta(
          proto.RmfProtos.Meta.Builder builderForValue) {
        if (MetaBuilder_ == null) {
          Meta_ = builderForValue.build();
          onChanged();
        } else {
          MetaBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.proto.Meta _meta = 1;</code>
       */
      public Builder mergeMeta(proto.RmfProtos.Meta value) {
        if (MetaBuilder_ == null) {
          if (Meta_ != null) {
            Meta_ =
              proto.RmfProtos.Meta.newBuilder(Meta_).mergeFrom(value).buildPartial();
          } else {
            Meta_ = value;
          }
          onChanged();
        } else {
          MetaBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.proto.Meta _meta = 1;</code>
       */
      public Builder clearMeta() {
        if (MetaBuilder_ == null) {
          Meta_ = null;
          onChanged();
        } else {
          Meta_ = null;
          MetaBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.proto.Meta _meta = 1;</code>
       */
      public proto.RmfProtos.Meta.Builder getMetaBuilder() {
        
        onChanged();
        return getMetaFieldBuilder().getBuilder();
      }
      /**
       * <code>.proto.Meta _meta = 1;</code>
       */
      public proto.RmfProtos.MetaOrBuilder getMetaOrBuilder() {
        if (MetaBuilder_ != null) {
          return MetaBuilder_.getMessageOrBuilder();
        } else {
          return Meta_ == null ?
              proto.RmfProtos.Meta.getDefaultInstance() : Meta_;
        }
      }
      /**
       * <code>.proto.Meta _meta = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          proto.RmfProtos.Meta, proto.RmfProtos.Meta.Builder, proto.RmfProtos.MetaOrBuilder> 
          getMetaFieldBuilder() {
        if (MetaBuilder_ == null) {
          MetaBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              proto.RmfProtos.Meta, proto.RmfProtos.Meta.Builder, proto.RmfProtos.MetaOrBuilder>(
                  getMeta(),
                  getParentForChildren(),
                  isClean());
          Meta_ = null;
        }
        return MetaBuilder_;
      }

      private proto.RmfProtos.Data Data_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          proto.RmfProtos.Data, proto.RmfProtos.Data.Builder, proto.RmfProtos.DataOrBuilder> DataBuilder_;
      /**
       * <code>.proto.Data _data = 2;</code>
       */
      public boolean hasData() {
        return DataBuilder_ != null || Data_ != null;
      }
      /**
       * <code>.proto.Data _data = 2;</code>
       */
      public proto.RmfProtos.Data getData() {
        if (DataBuilder_ == null) {
          return Data_ == null ? proto.RmfProtos.Data.getDefaultInstance() : Data_;
        } else {
          return DataBuilder_.getMessage();
        }
      }
      /**
       * <code>.proto.Data _data = 2;</code>
       */
      public Builder setData(proto.RmfProtos.Data value) {
        if (DataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          Data_ = value;
          onChanged();
        } else {
          DataBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.proto.Data _data = 2;</code>
       */
      public Builder setData(
          proto.RmfProtos.Data.Builder builderForValue) {
        if (DataBuilder_ == null) {
          Data_ = builderForValue.build();
          onChanged();
        } else {
          DataBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.proto.Data _data = 2;</code>
       */
      public Builder mergeData(proto.RmfProtos.Data value) {
        if (DataBuilder_ == null) {
          if (Data_ != null) {
            Data_ =
              proto.RmfProtos.Data.newBuilder(Data_).mergeFrom(value).buildPartial();
          } else {
            Data_ = value;
          }
          onChanged();
        } else {
          DataBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.proto.Data _data = 2;</code>
       */
      public Builder clearData() {
        if (DataBuilder_ == null) {
          Data_ = null;
          onChanged();
        } else {
          Data_ = null;
          DataBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.proto.Data _data = 2;</code>
       */
      public proto.RmfProtos.Data.Builder getDataBuilder() {
        
        onChanged();
        return getDataFieldBuilder().getBuilder();
      }
      /**
       * <code>.proto.Data _data = 2;</code>
       */
      public proto.RmfProtos.DataOrBuilder getDataOrBuilder() {
        if (DataBuilder_ != null) {
          return DataBuilder_.getMessageOrBuilder();
        } else {
          return Data_ == null ?
              proto.RmfProtos.Data.getDefaultInstance() : Data_;
        }
      }
      /**
       * <code>.proto.Data _data = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          proto.RmfProtos.Data, proto.RmfProtos.Data.Builder, proto.RmfProtos.DataOrBuilder> 
          getDataFieldBuilder() {
        if (DataBuilder_ == null) {
          DataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              proto.RmfProtos.Data, proto.RmfProtos.Data.Builder, proto.RmfProtos.DataOrBuilder>(
                  getData(),
                  getParentForChildren(),
                  isClean());
          Data_ = null;
        }
        return DataBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto.Res)
    }

    // @@protoc_insertion_point(class_scope:proto.Res)
    private static final proto.RmfProtos.Res DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto.RmfProtos.Res();
    }

    public static proto.RmfProtos.Res getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Res>
        PARSER = new com.google.protobuf.AbstractParser<Res>() {
      public Res parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Res(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Res> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Res> getParserForType() {
      return PARSER;
    }

    public proto.RmfProtos.Res getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_Empty_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_Empty_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_Meta_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_Meta_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_Data_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_Data_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_Req_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_Req_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_Res_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_Res_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017rmfProtos.proto\022\005proto\"\007\n\005Empty\"&\n\004Met" +
      "a\022\016\n\006sender\030\001 \001(\005\022\016\n\006height\030\002 \001(\005\"0\n\004Dat" +
      "a\022\032\n\005_meta\030\001 \001(\0132\013.proto.Meta\022\014\n\004data\030\002 " +
      "\001(\014\"!\n\003Req\022\032\n\005_meta\030\001 \001(\0132\013.proto.Meta\"=" +
      "\n\003Res\022\032\n\005_meta\030\001 \001(\0132\013.proto.Meta\022\032\n\005_da" +
      "ta\030\002 \001(\0132\013.proto.DataB\007\n\005protob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_proto_Empty_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_Empty_descriptor,
        new java.lang.String[] { });
    internal_static_proto_Meta_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_proto_Meta_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_Meta_descriptor,
        new java.lang.String[] { "Sender", "Height", });
    internal_static_proto_Data_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_proto_Data_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_Data_descriptor,
        new java.lang.String[] { "Meta", "Data", });
    internal_static_proto_Req_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_proto_Req_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_Req_descriptor,
        new java.lang.String[] { "Meta", });
    internal_static_proto_Res_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_proto_Res_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_Res_descriptor,
        new java.lang.String[] { "Meta", "Data", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
