// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rmfService.proto

package proto;

public final class RmfService {
  private RmfService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_Empty_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_Meta_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_Meta_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_Data_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_Data_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_Req_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_Req_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_Res_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_Res_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_RmfResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_RmfResult_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020rmfService.proto\022\005proto\032\017bbcProtos.pro" +
      "to\"\007\n\005Empty\"3\n\004Meta\022\016\n\006sender\030\001 \001(\005\022\016\n\006h" +
      "eight\030\002 \001(\005\022\013\n\003cid\030\003 \001(\005\"=\n\004Data\022\032\n\005_met" +
      "a\030\001 \001(\0132\013.proto.Meta\022\014\n\004data\030\002 \001(\014\022\013\n\003si" +
      "g\030\003 \001(\t\"!\n\003Req\022\032\n\005_meta\030\001 \001(\0132\013.proto.Me" +
      "ta\"=\n\003Res\022\032\n\005_meta\030\001 \001(\0132\013.proto.Meta\022\032\n" +
      "\005_data\030\002 \001(\0132\013.proto.Data\"&\n\tRmfResult\022\013" +
      "\n\003cid\030\001 \001(\005\022\014\n\004data\030\002 \001(\0142\213\001\n\003Rmf\0221\n\022Dis" +
      "seminateMessage\022\013.proto.Data\032\014.proto.Emp" +
      "ty\"\000\022)\n\010FastVote\022\r.proto.BbcMsg\032\014.proto." +
      "Empty\"\000\022&\n\nreqMessage\022\n.proto.Req\032\n.prot" +
      "o.Res\"\000B\t\n\005protoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          proto.BbcProtos.getDescriptor(),
        }, assigner);
    internal_static_proto_Empty_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_Empty_descriptor,
        new java.lang.String[] { });
    internal_static_proto_Meta_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_proto_Meta_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_Meta_descriptor,
        new java.lang.String[] { "Sender", "Height", "Cid", });
    internal_static_proto_Data_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_proto_Data_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_Data_descriptor,
        new java.lang.String[] { "Meta", "Data", "Sig", });
    internal_static_proto_Req_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_proto_Req_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_Req_descriptor,
        new java.lang.String[] { "Meta", });
    internal_static_proto_Res_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_proto_Res_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_Res_descriptor,
        new java.lang.String[] { "Meta", "Data", });
    internal_static_proto_RmfResult_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_proto_RmfResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_RmfResult_descriptor,
        new java.lang.String[] { "Cid", "Data", });
    proto.BbcProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
