// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: syncService.proto

package proto;

public final class SyncService {
  private SyncService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_proofedBlock_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_proofedBlock_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_frontSupport_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_frontSupport_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_subChainVersion_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_subChainVersion_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021syncService.proto\022\005proto\032\020blockchain.p" +
      "roto\032\017bbcProtos.proto\032\020rmfService.proto\"" +
      "A\n\014proofedBlock\022\027\n\001b\030\001 \001(\0132\014.proto.Block" +
      "\022\013\n\003cid\030\002 \001(\005\022\013\n\003Sig\030\003 \001(\t\"D\n\014frontSuppo" +
      "rt\022\013\n\003sid\030\001 \001(\005\022\n\n\002id\030\002 \001(\005\022\016\n\006height\030\003 " +
      "\001(\005\022\013\n\003sig\030\004 \001(\t\"g\n\017subChainVersion\022\021\n\tf" +
      "orkPoint\030\001 \001(\005\022\021\n\tsuggested\030\002 \001(\005\022\036\n\001v\030\003" +
      " \003(\0132\023.proto.proofedBlock\022\016\n\006sender\030\004 \001(" +
      "\0052B\n\013syncService\0223\n\014supportFront\022\023.proto" +
      ".frontSupport\032\014.proto.Empty\"\000B\t\n\005protoP\001" +
      "b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          proto.Blockchain.getDescriptor(),
          proto.BbcProtos.getDescriptor(),
          proto.RmfService.getDescriptor(),
        }, assigner);
    internal_static_proto_proofedBlock_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_proofedBlock_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_proofedBlock_descriptor,
        new java.lang.String[] { "B", "Cid", "Sig", });
    internal_static_proto_frontSupport_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_proto_frontSupport_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_frontSupport_descriptor,
        new java.lang.String[] { "Sid", "Id", "Height", "Sig", });
    internal_static_proto_subChainVersion_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_proto_subChainVersion_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_subChainVersion_descriptor,
        new java.lang.String[] { "ForkPoint", "Suggested", "V", "Sender", });
    proto.Blockchain.getDescriptor();
    proto.BbcProtos.getDescriptor();
    proto.RmfService.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
