// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wrbService.proto

package proto;

public final class WrbService {
  private WrbService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020wrbService.proto\022\005proto\032\013types.proto2m" +
      "\n\003Wrb\0228\n\022DisseminateMessage\022\022.proto.Bloc" +
      "kHeader\032\014.proto.Empty\"\000\022,\n\nreqMessage\022\r." +
      "proto.WrbReq\032\r.proto.WrbRes\"\000B\007\n\005protob\006" +
      "proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          proto.Types.getDescriptor(),
        }, assigner);
    proto.Types.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
