title = "configuration"

[system]
    n = 4
    f = 1

[setting]
    tmo = 1000
    tmoInterval = 100
    rmfBbcConfigPath = "config/bbcConfig/bbcFourServers"
    panicRBroadcastConfigPath = "src/main/resources/panicRBConfig"
    syncRBroadcastConfigPath = "src/main/resources/syncRBConfig"
    maxTransactionInBlock = 2

[server]
    id = 0
    ip = "127.0.0.1"
    rmfPort = 20000
    syncPort = 30000
    privateKey = """MIGNAgEAMBAGByqGSM49AgEGBSuBBAAKBHYwdAIBAQQg/ngTdAL+eZOyh4lilm6djqsl
                    RDHT5C60eLxRcEoNjAGgBwYFK4EEAAqhRANCAASeFQqtyOwJcJtYceofW2TeNg7rJBlW
                    L28GZn+tk32fz95JqVS3+iF6JdoM1clkRFLliyXSxEnS1iO4wzRKGQwm"""

    publicKey = """MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEnhUKrcjsCXCbWHHqH1tk3jYO6yQZVi9vBmZ/rZ
                    N9n8/eSalUt/oheiXaDNXJZERS5Ysl0sRJ0tYjuMM0ShkMJg=="""

[[cluster]]

    [cluster.s0]
        id = 0
        ip = "127.0.0.1"
        rmfPort = 20000
        syncPort = 30000
        publicKey ="""MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEnhUKrcjsCXCbWHHqH1tk3jYO6yQZVi9vBmZ/rZ
                       N9n8/eSalUt/oheiXaDNXJZERS5Ysl0sRJ0tYjuMM0ShkMJg=="""

    [cluster.s1]
        id = 1
        ip = "127.0.0.1"
        rmfPort = 20010
        syncPort = 30010
        publicKey = """MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEnhUKrcjsCXCbWHHqH1tk3jYO6yQZVi9vBmZ/rZ
                        N9n8/eSalUt/oheiXaDNXJZERS5Ysl0sRJ0tYjuMM0ShkMJg=="""
    [cluster.s2]
        id = 2
        ip = "127.0.0.1"
        rmfPort = 20020
        syncPort = 30020
        publicKey = """MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEnhUKrcjsCXCbWHHqH1tk3jYO6yQZVi9vBmZ/rZ
                        N9n8/eSalUt/oheiXaDNXJZERS5Ysl0sRJ0tYjuMM0ShkMJg=="""

    [cluster.s3]
        id = 3
        ip = "127.0.0.1"
        rmfPort = 20030
        syncPort = 30030
        publicKey="""MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEnhUKrcjsCXCbWHHqH1tk3jYO6yQZVi9vBmZ/rZ
                      N9n8/eSalUt/oheiXaDNXJZERS5Ysl0sRJ0tYjuMM0ShkMJg=="""
