title = "configuration"

[system]
    n = 4
    f = 1

[setting]
    tmo = 1000
    tmoInterval = 100
    rmfBbcConfigPath = "config/bbcConfig/bbcFourServers"
    maxTransactionInBlock = 1

[server]
    id = 0
    ip = "127.0.0.1"
    port = 20000
    privateKey = """MIICXAIBAAKBgQCTnNSo0xapOz4SZyWVYE/rZrB0gTa12U0L9O+8HoH3gA+plIRV
                bcfhEtOU8zlRZzl9AF9HUbVIF37ABCEkkqedBxO6/XNKsHOhqFGW891KdlUfUxoU
                vxgUEaWJcpL7h9KdpITXEyawZN1q6GuoLKJF938BUutcsBoTCUdNgMPpewIDAQAB
                AoGAIQ0SiKKLBmVfZpt1zNZ9zoV1qQBtkZYQLEcxjnt+Oj6QQzYf00j7Yifm/Ajh
                oppsQtLcgomG/5dTKAdErH2xzZsVe9zPLpH0YRCQgvH156iMChjpuTn2juuKL9Jn
                N3LyZ0Qh16TJfb2D9FPk2Hy8ivAZ0AXaKDrWfnLbOlA/P4ECQQD716eU8izEfgqf
                sXbdFkALEXV7XDS6Qv12sIbF3GmqeB4hIrMXai4vcYCR+bwjwrHQOmtPzYPMb/CO
                afc562xhAkEAlgytK6uFY/hUIUQxxVNYviwQwaiNyORs2xGQHXb/8ehCVrzT7lFz
                rRrvQpI5myfzHgIvXebJajqiKOjmkBdDWwJBAPvSvGOXdWRVlFHypiSUpx1qK8ta
                e+70JXaVNW6L46ztx1Li26nCJsSR/jn5OkOX3y2T/NIjcnLuS+Bb3TYxToECQGC/
                wbTjvnmMOCrO/sx+Bj1wykkkNm+vIaVLOMJW5YcEPCoTTQ9gQ5b9RAKHqE8rvi2+
                OO5yDbLKJZ79NRT5evsCQAR+76wykMXZN907C/JYKdq3N0bBFW9KEenddoiKd2NP
                a+wqpz2/4EYkI4BawZ3gUZtHoxSvw8tWS2Io0SpU+Rs="""

    publicKey = """MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCTnNSo0xapOz4SZyWVYE/rZrB0
                  gTa12U0L9O+8HoH3gA+plIRVbcfhEtOU8zlRZzl9AF9HUbVIF37ABCEkkqedBxO6
                  /XNKsHOhqFGW891KdlUfUxoUvxgUEaWJcpL7h9KdpITXEyawZN1q6GuoLKJF938B
                  UutcsBoTCUdNgMPpewIDAQAB"""

[[RMFcluster]]

    [RMFcluster.s0]
        id = 0
        ip = "127.0.0.1"
        port = 20000
        publicKey = """MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCTnNSo0xapOz4SZyWVYE/rZrB0
                      gTa12U0L9O+8HoH3gA+plIRVbcfhEtOU8zlRZzl9AF9HUbVIF37ABCEkkqedBxO6
                      /XNKsHOhqFGW891KdlUfUxoUvxgUEaWJcpL7h9KdpITXEyawZN1q6GuoLKJF938B
                      UutcsBoTCUdNgMPpewIDAQAB"""

    [RMFcluster.s1]
        id = 1
        ip = "127.0.0.1"
        port = 20010
        publicKey = """MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCTnNSo0xapOz4SZyWVYE/rZrB0
                      gTa12U0L9O+8HoH3gA+plIRVbcfhEtOU8zlRZzl9AF9HUbVIF37ABCEkkqedBxO6
                      /XNKsHOhqFGW891KdlUfUxoUvxgUEaWJcpL7h9KdpITXEyawZN1q6GuoLKJF938B
                      UutcsBoTCUdNgMPpewIDAQAB"""

    [RMFcluster.s2]
        id = 2
        ip = "127.0.0.1"
        port = 20020
        publicKey = """MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCTnNSo0xapOz4SZyWVYE/rZrB0
                      gTa12U0L9O+8HoH3gA+plIRVbcfhEtOU8zlRZzl9AF9HUbVIF37ABCEkkqedBxO6
                      /XNKsHOhqFGW891KdlUfUxoUvxgUEaWJcpL7h9KdpITXEyawZN1q6GuoLKJF938B
                      UutcsBoTCUdNgMPpewIDAQAB"""

    [RMFcluster.s3]
        id = 3
        ip = "127.0.0.1"
        port = 20030
        publicKey="""MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCTnNSo0xapOz4SZyWVYE/rZrB0
                  gTa12U0L9O+8HoH3gA+plIRVbcfhEtOU8zlRZzl9AF9HUbVIF37ABCEkkqedBxO6
                  /XNKsHOhqFGW891KdlUfUxoUvxgUEaWJcpL7h9KdpITXEyawZN1q6GuoLKJF938B
                  UutcsBoTCUdNgMPpewIDAQAB"""

