title = "configuration"

[system]
    n = 1
    f = 0


[setting]
    tmo = 1000
    tmoInterval = 100
    rmfBbcConfigPath = "config/singleServer/bbcConfig"
    panicRBroadcastConfigPath = "config/singleServer/panicRBConfig"
    syncRBroadcastConfigPath = "config/singleServer/syncRBConfig"
    maxTransactionInBlock = 2
    caRootPath = ""
    fastMode = true

[server]
    id = 0
    ip = "127.0.0.1"
    rmfPort = 20000
    privateKey = """MIGNAgEAMBAGByqGSM49AgEGBSuBBAAKBHYwdAIBAQQg/ngTdAL+eZOyh4lilm6djqsl
                    RDHT5C60eLxRcEoNjAGgBwYFK4EEAAqhRANCAASeFQqtyOwJcJtYceofW2TeNg7rJBlW
                    L28GZn+tk32fz95JqVS3+iF6JdoM1clkRFLliyXSxEnS1iO4wzRKGQwm"""

    publicKey = """MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEnhUKrcjsCXCbWHHqH1tk3jYO6yQZVi9vBmZ/rZ
                    N9n8/eSalUt/oheiXaDNXJZERS5Ysl0sRJ0tYjuMM0ShkMJg=="""

    TlsPrivKeyPath = "config/singleServer/sslConfig/key.pem"
    TlsCertPath = "config/singleServer/sslConfig/cert.pem"
[[cluster]]

    [cluster.s0]
        id = 0
        ip = "127.0.0.1"
        rmfPort = 20000
        publicKey ="""MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEnhUKrcjsCXCbWHHqH1tk3jYO6yQZVi9vBmZ/rZ
                       N9n8/eSalUt/oheiXaDNXJZERS5Ysl0sRJ0tYjuMM0ShkMJg=="""
