title = "configuration"
[system]
    n = 16
    f = 5
    c = 1
    testing = true
    txSize = 0

[setting]
    tmo = 1000
    tmoInterval = 100
    ABConfigPath = "src/main/resources/ABConfig"
    maxTransactionInBlock = 1000
    caRootPath = ""
    fastMode = true

[server]
    privateKey = """MIGNAgEAMBAGByqGSM49AgEGBSuBBAAKBHYwdAIBAQQg/ngTdAL+eZOyh4lilm6djqsl
                    RDHT5C60eLxRcEoNjAGgBwYFK4EEAAqhRANCAASeFQqtyOwJcJtYceofW2TeNg7rJBlW
                    L28GZn+tk32fz95JqVS3+iF6JdoM1clkRFLliyXSxEnS1iO4wzRKGQwm"""

    TlsPrivKeyPath = "src/main/resources/sslConfig/server.pem"
    TlsCertPath = "src/main/resources/sslConfig/server.crt"


[[cluster]]
      [cluster.s0]
            id = 0
            ip = "172.31.2.19"
            wrbPort = 30000
            commPort = 30010
            obbcPort = 30020
            publicKey ="""MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEnhUKrcjsCXCbWHHqH1tk3jYO6yQZVi9vBmZ/rZ
                               N9n8/eSalUt/oheiXaDNXJZERS5Ysl0sRJ0tYjuMM0ShkMJg=="""
    
      [cluster.s1]
            id = 1
            ip = "172.31.0.21"
            wrbPort = 30000
            commPort = 30010
            obbcPort = 30020
            publicKey ="""MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEnhUKrcjsCXCbWHHqH1tk3jYO6yQZVi9vBmZ/rZ
                               N9n8/eSalUt/oheiXaDNXJZERS5Ysl0sRJ0tYjuMM0ShkMJg=="""
    
      [cluster.s2]
            id = 2
            ip = "172.31.2.18"
            wrbPort = 30000
            commPort = 30010
            obbcPort = 30020
            publicKey ="""MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEnhUKrcjsCXCbWHHqH1tk3jYO6yQZVi9vBmZ/rZ
                               N9n8/eSalUt/oheiXaDNXJZERS5Ysl0sRJ0tYjuMM0ShkMJg=="""
    
      [cluster.s3]
            id = 3
            ip = "172.31.9.18"
            wrbPort = 30000
            commPort = 30010
            obbcPort = 30020
            publicKey ="""MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEnhUKrcjsCXCbWHHqH1tk3jYO6yQZVi9vBmZ/rZ
                               N9n8/eSalUt/oheiXaDNXJZERS5Ysl0sRJ0tYjuMM0ShkMJg=="""
    
      [cluster.s4]
            id = 4
            ip = "172.31.4.11"
            wrbPort = 30000
            commPort = 30010
            obbcPort = 30020
            publicKey ="""MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEnhUKrcjsCXCbWHHqH1tk3jYO6yQZVi9vBmZ/rZ
                               N9n8/eSalUt/oheiXaDNXJZERS5Ysl0sRJ0tYjuMM0ShkMJg=="""
    
      [cluster.s5]
            id = 5
            ip = "172.31.13.15"
            wrbPort = 30000
            commPort = 30010
            obbcPort = 30020
            publicKey ="""MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEnhUKrcjsCXCbWHHqH1tk3jYO6yQZVi9vBmZ/rZ
                               N9n8/eSalUt/oheiXaDNXJZERS5Ysl0sRJ0tYjuMM0ShkMJg=="""
    
      [cluster.s6]
            id = 6
            ip = "172.31.2.10"
            wrbPort = 30000
            commPort = 30010
            obbcPort = 30020
            publicKey ="""MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEnhUKrcjsCXCbWHHqH1tk3jYO6yQZVi9vBmZ/rZ
                               N9n8/eSalUt/oheiXaDNXJZERS5Ysl0sRJ0tYjuMM0ShkMJg=="""
    
      [cluster.s7]
            id = 7
            ip = "172.31.7.10"
            wrbPort = 30000
            commPort = 30010
            obbcPort = 30020
            publicKey ="""MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEnhUKrcjsCXCbWHHqH1tk3jYO6yQZVi9vBmZ/rZ
                               N9n8/eSalUt/oheiXaDNXJZERS5Ysl0sRJ0tYjuMM0ShkMJg=="""
    
      [cluster.s8]
            id = 8
            ip = "172.31.14.30"
            wrbPort = 30000
            commPort = 30010
            obbcPort = 30020
            publicKey ="""MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEnhUKrcjsCXCbWHHqH1tk3jYO6yQZVi9vBmZ/rZ
                               N9n8/eSalUt/oheiXaDNXJZERS5Ysl0sRJ0tYjuMM0ShkMJg=="""
    
      [cluster.s9]
            id = 9
            ip = "172.31.5.31"
            wrbPort = 30000
            commPort = 30010
            obbcPort = 30020
            publicKey ="""MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEnhUKrcjsCXCbWHHqH1tk3jYO6yQZVi9vBmZ/rZ
                               N9n8/eSalUt/oheiXaDNXJZERS5Ysl0sRJ0tYjuMM0ShkMJg=="""
    
      [cluster.s10]
            id = 10
            ip = "172.31.15.24"
            wrbPort = 30000
            commPort = 30010
            obbcPort = 30020
            publicKey ="""MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEnhUKrcjsCXCbWHHqH1tk3jYO6yQZVi9vBmZ/rZ
                               N9n8/eSalUt/oheiXaDNXJZERS5Ysl0sRJ0tYjuMM0ShkMJg=="""
    
      [cluster.s11]
            id = 11
            ip = "172.31.10.30"
            wrbPort = 30000
            commPort = 30010
            obbcPort = 30020
            publicKey ="""MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEnhUKrcjsCXCbWHHqH1tk3jYO6yQZVi9vBmZ/rZ
                               N9n8/eSalUt/oheiXaDNXJZERS5Ysl0sRJ0tYjuMM0ShkMJg=="""
    
      [cluster.s12]
            id = 12
            ip = "172.31.2.142"
            wrbPort = 30000
            commPort = 30010
            obbcPort = 30020
            publicKey ="""MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEnhUKrcjsCXCbWHHqH1tk3jYO6yQZVi9vBmZ/rZ
                               N9n8/eSalUt/oheiXaDNXJZERS5Ysl0sRJ0tYjuMM0ShkMJg=="""
    
      [cluster.s13]
            id = 13
            ip = "172.31.9.143"
            wrbPort = 30000
            commPort = 30010
            obbcPort = 30020
            publicKey ="""MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEnhUKrcjsCXCbWHHqH1tk3jYO6yQZVi9vBmZ/rZ
                               N9n8/eSalUt/oheiXaDNXJZERS5Ysl0sRJ0tYjuMM0ShkMJg=="""
    
      [cluster.s14]
            id = 14
            ip = "172.31.8.139"
            wrbPort = 30000
            commPort = 30010
            obbcPort = 30020
            publicKey ="""MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEnhUKrcjsCXCbWHHqH1tk3jYO6yQZVi9vBmZ/rZ
                               N9n8/eSalUt/oheiXaDNXJZERS5Ysl0sRJ0tYjuMM0ShkMJg=="""
    
      [cluster.s15]
            id = 15
            ip = "172.31.6.140"
            wrbPort = 30000
            commPort = 30010
            obbcPort = 30020
            publicKey ="""MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEnhUKrcjsCXCbWHHqH1tk3jYO6yQZVi9vBmZ/rZ
                               N9n8/eSalUt/oheiXaDNXJZERS5Ysl0sRJ0tYjuMM0ShkMJg=="""
    
