title = "configuration"
[system]
    n = 4
    f = 1
    c = 1
    testing = true
    txSize = 0

[setting]
    tmo = 1000
    tmoInterval = 100
    ABConfigPath = "src/main/resources/ABConfig"
    maxTransactionInBlock = 1000
    caRootPath = ""
    fastMode = true

[server]
    privateKey = """MIGNAgEAMBAGByqGSM49AgEGBSuBBAAKBHYwdAIBAQQg/ngTdAL+eZOyh4lilm6djqsl
                    RDHT5C60eLxRcEoNjAGgBwYFK4EEAAqhRANCAASeFQqtyOwJcJtYceofW2TeNg7rJBlW
                    L28GZn+tk32fz95JqVS3+iF6JdoM1clkRFLliyXSxEnS1iO4wzRKGQwm"""

    TlsPrivKeyPath = "src/main/resources/sslConfig/server.pem"
    TlsCertPath = "src/main/resources/sslConfig/server.crt"


[[cluster]]
      [cluster.s0]
            id = 0
            ip = "172.31.18.74"
            wrbPort = 30000
            commPort = 30010
            obbcPort = 30020
            publicKey ="""MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEnhUKrcjsCXCbWHHqH1tk3jYO6yQZVi9vBmZ/rZ
                               N9n8/eSalUt/oheiXaDNXJZERS5Ysl0sRJ0tYjuMM0ShkMJg=="""
    
      [cluster.s1]
            id = 1
            ip = "172.31.30.184"
            wrbPort = 30000
            commPort = 30010
            obbcPort = 30020
            publicKey ="""MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEnhUKrcjsCXCbWHHqH1tk3jYO6yQZVi9vBmZ/rZ
                               N9n8/eSalUt/oheiXaDNXJZERS5Ysl0sRJ0tYjuMM0ShkMJg=="""
    
      [cluster.s2]
            id = 2
            ip = "172.31.31.96"
            wrbPort = 30000
            commPort = 30010
            obbcPort = 30020
            publicKey ="""MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEnhUKrcjsCXCbWHHqH1tk3jYO6yQZVi9vBmZ/rZ
                               N9n8/eSalUt/oheiXaDNXJZERS5Ysl0sRJ0tYjuMM0ShkMJg=="""
    
      [cluster.s3]
            id = 3
            ip = "172.31.19.75"
            wrbPort = 30000
            commPort = 30010
            obbcPort = 30020
            publicKey ="""MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEnhUKrcjsCXCbWHHqH1tk3jYO6yQZVi9vBmZ/rZ
                               N9n8/eSalUt/oheiXaDNXJZERS5Ysl0sRJ0tYjuMM0ShkMJg=="""
    
